### ISSUE TITLE
vim completion shows errors

### ISSUE THREAD

**Issue by antoineco** [Eriner/zim#105]
- Zim commit ref: `b55ed8ad`
- gist of .zimrc: (default)
- Zsh version: `5.2 (x86_64-apple-darwin15.6.0)`
- gist of .zshrc: 
```
#
# User configuration sourced by interactive shells
#

# Source zim
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi

export EDITOR='vim'
export VISUAL='vim'
```
- $(uname -mosr): `x86_64 Darwin 16.1.0`

Description
-----------
Instead of completing the path, the autocompletion generates the following error after typing the "vim" or "nvim" word:
```
[me@myhost ~]$ vim Doc...
_arguments:451: _vim_files: function definition file not found
_arguments:451: _vim_files: function definition file not found
```

Steps to reproduce
------------------
Type "vim (space) (Tab)" anywhere.

Images or other information
---------------------------
* Does not happen after typing just "vi"
* The "steeef" prompt mutes these errors

**Comment by Plloi** [comment]
Try removing ~/.zcompdump and restarting your shell

**Comment by Eriner** [comment]
@Plloi's suggestion is a good one. `_vim_files` is not a function provided by the completion module. Also, a quick search of your issue immediately revealed the same solution @Plloi has proposed.

https://github.com/robbyrussell/oh-my-zsh/issues/518

http://unix.stackexchange.com/questions/280622/zsh-fails-at-path-completition-when-command-is-vim#280626

In the future, I recommend searching for the issue specifically. To find the link I posted above, my search query was:

> "_vim_files" zsh

**Comment by Eriner** [comment]
Oh, I almost forgot! After doing that, I suggest you run `source .zlogin` (from a new zsh shell) to re-bytecompile your `.zcompdump` file.

**Comment by antoineco** [comment]
I'm sorry @Eriner and @Plloi, believe me I really did delete my `.zcompdump` file before opening that issue. In the meantime I moved some `.z*` files around and created some symlinks, which somehow made the issue appear again and made me believe the behaviour was consistent.

I should have deleted `.zcompdump` again *after* playing around with my `.z*` files, which indeed solved the problem. Thanks for pointing that out guys!
