### ISSUE TITLE
(eval):1: bad option: -=

### ISSUE THREAD

**Issue by slaecker** [Eriner/zim#106]
Hi,

I backed up and deleted my current zsh configuration files to start clean and followed the installation process on the README.

After starting a new terminal (terminix or gnome-terminal) I see an eval error before the prompt:

> (eval):1: bad option: -=
>  slaecker@linux-hizr ~

**Comment by Eriner** [comment]
Please provide the information requested in the issue template and re-open a new issue. This is nowhere near enough information for me to assist you.
