### ISSUE TITLE
``(eval):1: bad option: -='' when starting new terminal

### ISSUE THREAD

**Issue by slaecker** [Eriner/zim#107]
- Zim commit ref: ?
- gist of .zimrc: https://gist.github.com/slaecker/5bd770daa21a25c814312b394ed25fd3
- Zsh version: 5.0.5
- gist of .zshrc: https://gist.github.com/slaecker/cbf30bb91c28617f5a861d89b1651515
- $(uname -mosr): Linux 4.1.34-33-default x86_64 GNU/Linux

Description
-----------
I backed up and deleted my current zsh configuration files to start clean and followed the installation process on the README.

Everytime I start a new terminal (tried with terminix and gnome-terminal) I see an eval error before the prompt:

> (eval):1: bad option: -=
> slaecker@linux-hizr ~

Steps to reproduce
------------------

1. Delete existing zsh config to start clean
1. Follow the [installation steps from the README](https://github.com/Eriner/zim/blob/master/README.md#installation)
1. Start a new terminal (in my case terminix or gnome-terminal)
1. above the prompt the eval error is shown: ``(eval):1: bad option: -=``

Images or other information
---------------------------

![2016-12-07_zim_issue_gnome-terminal](https://cloud.githubusercontent.com/assets/8582375/20966391/50c23ec6-bc7a-11e6-89e1-e421da6e9b1e.png)
![2016-12-07_zim_issue_terminix](https://cloud.githubusercontent.com/assets/8582375/20966392/50c61b0e-bc7a-11e6-87d3-84a08d81499c.png)

**Comment by Eriner** [comment]
> Zsh version: 5.0.5

I'm not sure exactly what the problem is, but whenever I see a version of zsh that old, my first recommendation is always to grab a newer version of zsh and try that. See if the problem persists.

> on Jan 5, 2014  -  zsh-5.0.5

Zsh version 5.0.5 was released almost two years ago.

**Comment by slaecker** [comment]
Well, that's the last piece I needed to switch back to Arch Linux. Looks like switching from Arch to any other distribution is just a pain sooner or later. Since I've been using Arch I forgot to care about software versions ;)
