### ISSUE TITLE
inconsistent bindkey mode 

### ISSUE THREAD

**Issue by antoineco** [Eriner/zim#108]
- Zim commit ref: `b55ed8ad`
- gist of .zimrc: (default)
- Zsh version: `5.2 (x86_64-apple-darwin15.6.0)`
- gist of .zshrc: 
```
export EDITOR='vim'
export VISUAL='vim'
```
- $(uname -mosr): `x86_64 Darwin 16.1.0`

Description
-----------
By default zle operates in `vi` mode if the EDITOR environment variable is set to anything containing /vi/.
When using zim in my environment, the bindkey mode defaults to:
* `emacs` in a plain terminal session
* `vi` in a tmux session

Without zim, the zle mode is set to `vi` consistently, which should be the expected behaviour.

Steps to reproduce
------------------
1. Set `export EDITOR='vim'` in your .zshrc
2. Open a new terminal window
3. Confirm you're in emacs mode:
    ```
    ❯ bindkey -lL main
    bindkey -A emacs main
    ```
4. Open a tmux session
5. Confirm you're in vi mode:
    ```
    ❯ bindkey -lL main
    bindkey -A viins main
    ```

**Comment by Eriner** [comment]
Excellent bug report! Providing steps to reproduce/show the problem is the type of thing I'm looking for! Spot on!

That said, I'm unable to reproduce your results ;P

Outside of tmux, in a normal shell:
```
 ~  bindkey -lL main
bindkey -A viins main
 ~  print ${EDITOR}
nvim
```

Inside tmux:
```
 ~  bindkey -lL main
bindkey -A viins main
 ~  print ${EDITOR}
nvim
```

**Comment by antoineco** [comment]
Would have been too easy :) 
I can reproduce on both my Macbook and Linux machine (Terminal.app and Gnome terminal).

Just to be sure, you're not manipulating the `bindkey` mappings anywhere in your .Z files, are you?
Did you try with a minimal .zshrc? Mine only exports the EDITOR and VISUAL env vars below the call to the zim init script.

**Comment by antoineco** [comment]
One step further: tmux can be taken out of the equation.

1. When I open my terminal emulator (either Terminal.app or GNOME Terminal):
   ```
   ❯ bindkey -lL main
   bindkey -A emacs main
   ```
2. When I fork my session:
   ```
   ❯ zsh -il
   ❯ bindkey -lL main
   bindkey -A viins main
   ```

- If I comment out the line `source ${ZDOTDIR:-${HOME}}/.zim/init.zsh` in my `.zshrc` file, the terminal always starts with the `viins` bindkey.
- Likewise, if I set `EDITOR=vim` **before** sourcing zim, zle starts in 'vi' mode.

I'll try to find where Zim interfers, for now the workaround mentioned above does the trick.

**Comment by antoineco** [comment]
I found the source of the issue.

Whenever the `bindkey` command is executed somewhere in the .zshrc file or any sourced script (any command, even `bindkey -l`) Zsh will skip trying to guess the most appropriate zle mode and default to `emacs`.

The `input` Zim module [sets a couple of keybinding using the `bindkey` command](
https://github.com/Eriner/zim/blob/d91d9e3efe5defbcc13a0fc8968e2f3919cffc2a/modules/input/init.zsh#L50), therefore bindkey is not set to 'viins' if `EDITOR=vim` is set *after* sourcing Zim, but it works if it's set *before*.

When the session is forked (see my previous comments), the `EDITOR` env var is already exported from the parent session, so the position of the `export` command in the `.zshrc` file has no influence anymore.

---

**Test log 1**

```zsh
# .zshrc

echo -- execute bindkey before setting EDITOR --
bindkey -lL main
export EDITOR='vim'
export VISUAL='vim'

#... source zim
```
```
Last login: Fri Dec 16 16:21:24 on ttys000
-- execute bindkey before setting EDITOR --
bindkey -A emacs main

~
❯ bindkey -lL main
bindkey -A emacs main
```

---

**Test log 2**

```zsh
# .zshrc

export EDITOR='vim'
export VISUAL='vim'
echo -- execute bindkey after setting EDITOR --
bindkey -lL main

#... source zim
```
```
Last login: Fri Dec 16 16:27:19 on ttys000
-- execute bindkey after setting EDITOR --
bindkey -A viins main

~
❯ bindkey -lL main                                                                        
bindkey -A viins main
```

---

Note to prezto users who get confused by this behaviour: prezto explicitly sets the key layout in its [editor module](https://github.com/sorin-ionescu/prezto/blob/4f19700919c8ebbaf75755fc0d03716d13183f49/modules/editor/init.zsh#L319-L327). Zim doesn't.
