### ISSUE TITLE
Officially supported global installation

### ISSUE THREAD

**Issue by addisonamiri** [Eriner/zim#11]
It would also be cool if there were user zshrc and zimrc templates for the global install from the AUR package. I feel like I'm hacking this together and it doesn't seem like the best way I should be doing this.

**Comment by Eriner** [comment]
I didn't make the AUR package, though, it's neat that someone else did. I'm not entirely sure what you're asking here. The templates (or any configuration, for that matter) will read first from the global files, then from the user files. I haven't looked into how the zim package in the AUR is handling this, as I personally believe a global installation isn't the best solution. It's ideal to clone the repo; that way it's easy to update and you're not re-cloning the whole repo on every install. Plus, you're right, doing this globally adds an additional level of complexity (and is something only Arch users are doing).

**Comment by addisonamiri** [comment]
If you think it's out of scope for the project then don't worry about it.
I'll figure out a way to get this working well enough.

If you're curious is looks like the maintainer just ran a few sed commands
on the config files and installed them to `/etc/zsh/*` and `/usr/lib/zim`.
It's the same way your fork of prezto is installed by its AUR package. I
just wanted a sane root shell but you're probably right, a global install
isn't the best. Thanks for the project. I just switched and it's working
fine for me :)

**Comment by Eriner** [comment]
Yes, it's similar to the `prezto-git` package. Glad to know it's working out well for you.
