### ISSUE TITLE
[lean prompt] fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by Brottweiler** [Eriner/zim#110]
- Zim commit ref: b55ed8ad27e481891d6f0811eed67d92316c5377
- gist of .zimrc: [gist/f9792ae9fb490583ce5db1c35e2cd223#file-zimrc](https://gist.github.com/anonymous/f9792ae9fb490583ce5db1c35e2cd223#file-zimrc)
- Zsh version: `5.2-2`
- gist of .zshrc: [gist/f9792ae9fb490583ce5db1c35e2cd223#file-zshrc](https://gist.github.com/anonymous/f9792ae9fb490583ce5db1c35e2cd223#file-zshrc)
- $(uname -mosr): `Linux 4.8.12-3-ARCH x86_64 GNU/Linux`

Description
-----------
With ZIM enabled (with or without `git` module it seems), running `git init` gives this error

```sh
% git init
Initialized empty Git repository in /home/brott/Desktop/testgit/.git/
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.                                               
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Without ZIM, it gives this

```sh
% git init
Initialized empty Git repository in /home/brott/Desktop/testgit2/.git/
```

Steps to reproduce
------------------
1. Create new folder
2. run `git init` inside it

Images or other information
---------------------------
- https://stackoverflow.com/questions/12267912/git-fatal-ambiguous-argument-head-unknown-revision-or-path-not-in-the-workin

Related to these?
- https://github.com/Eriner/zim/blob/master/modules/git/functions/git_prompt_info
- https://github.com/Eriner/zim/blob/master/modules/git/functions/git_current_branch

**Comment by Plloi** [comment]
some brief experimentation show this is related to the lean prompt theme

**Comment by Brottweiler** [comment]
@Plloi You're right, I just switched prompt and it had no issues.

**Comment by Brottweiler** [comment]
I created a new issue over at https://github.com/miekg/lean/issues/12.

**Comment by Eriner** [comment]
Yep, seems to be an upstream problem. Once the issue is fixed, I'll update the submodule and push to master.

**Comment by Brottweiler** [comment]
@Eriner https://github.com/miekg/lean/issues/12#issuecomment-266269672

**Comment by Eriner** [comment]
Pushed, thanks!
