### ISSUE TITLE
fasd completion not working

### ISSUE THREAD

**Issue by justbur** [Eriner/zim#111]
- Zim commit ref: b55ed8ad27e481891d6f0811eed67d92316c5377
- gist of .zimrc: https://gist.github.com/justbur/d90f83a17186a186f228bc60dc5820fa
- Zsh version: 5.2
- gist of .zshrc: (just sources .zim/init.zsh)
- $(uname -mosr): Linux 4.8.11-300.fc25.x86_64 x86_64 GNU/Linux

Description
-----------

It appears that the fasd module sets up completion for the fasd commands. It doesn't appear to be working for me. 

Steps to reproduce
------------------

 1. `z [beginning of some dir]<tab><tab>` has no effect regardless of what I put in for the name of the directory.

Images or other information
---------------------------

**Comment by spencersteers** [comment]
Would love to take a stab at this - anyone familiar enough to know where to start?
