### ISSUE TITLE
'prompt -p' breaks the prompt line

### ISSUE THREAD

**Issue by alshakh** [Eriner/zim#112]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:

- Zim commit ref: zsh-zim-git r250.b55ed8a-1
- gist of .zimrc: EMPTY
- Zsh version: 5.2
- gist of .zshrc: EMPTY
- $(uname -mosr):Linux 4.8.10-1-ARCH x86_64 GNU/Linux

Description
-----------

On a clean install from AUR, running 'prompt -p' doesn't show the themese correctly and breaks the current prompt. After running the command the prompt becomes:
```
$purpleshak${${reset_color} at $orangesaber${${reset_color} in $limegreen~${${reset_color} $vcs_info_msg_0_$(virtualenv_info)${reset_color}
$ (CURSOR)
```

Steps to reproduce
------------------
current theme is the default (steeph)
Just run 'prompt -p'

Images or other information
---------------------------

![prompt example](https://cloud.githubusercontent.com/assets/3307612/21076091/c6963146-bf33-11e6-9112-c7f16e68e646.png)

**Comment by Plloi** [comment]
it's liquidprompt.

You can verify by running `prompt -p liquidprompt`

**Comment by Eriner** [comment]
I can reproduce this issue.

**Comment by chrissound** [comment]
In case it helps anyone:
```
# prompt -p liquidprompt

No sensors found!
Make sure you loaded all the kernel drivers you need.
Try sensors-detect to find out which these are.
liquidprompt theme:
[root@li1524-158:~] # command arg1 arg2 ... argn


$purpleroot${${reset_color} at $orangeli1524-158${${reset_color} in $limegreen~${${reset_color} $vcs_info_msg_0_$(virtualenv_info)${reset_color}
```
