### ISSUE TITLE
Shift+Tab doesn't cycle navigation backwards

### ISSUE THREAD

**Issue by antonshiryaev** [Eriner/zim#114]
Not sure if it's a bug or an oversight, but shouldn't be too hard to fix either way.

**Comment by Eriner** [comment]
Shift+tab cycles backwards for me in the menu expansion.

**Comment by antonshiryaev** [comment]
[zshrc.zip](https://github.com/Eriner/zim/files/671951/zshrc.zip)
Here are my .inputrc and .zshrc files. I don't think much else could be the cause. I'm on ZSH 5.3.1, macOS 10.12.2, iTerm 3.0.12.

**Comment by Eriner** [comment]
Are you still experiencing this issue?

**Comment by antonshiryaev** [comment]
Yes, in fact. In fact, it's reproduced on a different machine with a mostly clean set up, so I suspect it's due to `set editing-mode viI` in my .inputrc. I've worked around it by adding `bindkey '^[[Z' reverse-menu-complete` in my .zshrc.

**Comment by antonshiryaev** [comment]
Figured something out: if `set -o vi` goes after the aforementioned bind, shift+tab doesn't work. Apparently it's overwritten.
