### ISSUE TITLE
Install ZIM without Git

### ISSUE THREAD

**Issue by Infern1** [Eriner/zim#116]
Description
-----------
It should possible to install ZIM without git. Now it's not possible since if you get the zip from github it doesn't contain the external  references.

Other option would to make some releases which can be downloaded as zip/tar.gz

**Comment by Eriner** [comment]
What is the case for this? How often don't you have access to git?

**Comment by Infern1** [comment]
Since why should I install git and all dependencies on a machine where never do any development git thing?

Creating a small script for creating a release shouldn't be that hard?

**Comment by Brottweiler** [comment]
I understand you probably don't want to "bloat" your system... but think of it as any package which has dependencies... this one has `git`, because it is used to install and update it.
