### ISSUE TITLE
prompt module previews strangeness.

### ISSUE THREAD

**Issue by beanaroo** [Eriner/zim#12]
I apologize for the horrible title, I don't really know what's going on, broken prompt module or just a broken theme or two, please rename as appropriate.
I have installed zsh-zim-git via the Arch user repositories. No custom configuration.

Using the `prompt -p` command:

* steeef is not  included in previewed list, depending on the active prompt.
* Preview for liquidprompt is the current active prompt, also seems to depend on active prompt.
* Some prompt previews are broken when previewing after switching to suse theme. I have not confirmed with all the others.
* After running `prompt -p`, active prompt switches to liquidprompt and doesn't change appearance even when changing theme and confirming with `prompt -c`

**Comment by Eriner** [comment]
Yeah, I can verify some of these problems. I'll look into it tomorrow. Likely some prompts are polluting the environment and causing this issue. Thanks for the report!

**Comment by Eriner** [comment]
It looks like will probably be a pain to fix. 

I'll spend some time on it throughout the week, but as this doesn't impair day-to-day functionality and will likely require a hefty time investment to fix, it's not on the top of my to-do list.

If there is anyone who works with prompts frequently (and can quickly determine the issue), I'd be happy to PR.
