### ISSUE TITLE
Slowdown after adding a few items to .zshrc

### ISSUE THREAD

**Issue by akrueger** [Eriner/zim#121]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:

In a terminal, run `zmanage info` and paste the output below:

```
Zim commit ref:   b021ba6
Zsh version:      zsh 5.3.1 (x86_64-apple-darwin16.3.0)
System info:      Darwin adjmbpnb004.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

```

- gist of .zimrc: https://gist.github.com/akrueger/1d7df97b9ab0d9eb5e4040ae9cee15b1
- gist of .zshrc: https://gist.github.com/akrueger/83a68cd2117b5117b038206eb1bd540d

Description
-----------
I added a few items to the .zshrc and the terminal now starts up quite a bit slower. I'm not sure if .zshrc is the appropriate place to be adding aliases, environment variables and path locations. When I remove these items, the terminal is extremely snappy.

Steps to reproduce
------------------
Add items to .zshrc and open new terminal window or tab in terminal.app

Images or other information
---------------------------

**Comment by Tmplt** [comment]
I have a lot of extra stuff in my zsh configs without any slow-downs. Whether it impacts shell start-up time depends on what you add.

From your `.zshrc` I can only guess that `eval "$(jenv init -)"` is the perpetrator. I'm unable to test the command myself, so try commenting that line out. Is the start-up time still long?

**Comment by akrueger** [comment]
It seems to perhaps be a combination of:
`eval "$(jenv init -)"` and
`export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"`

I have commented everything incrementally and those are the only two that seem to have much of an effect (although neither one seems to be wholly responsible).

I just wanted to make sure that the `.zshrc` was the proper place for these types of additions. I didn't know if `zim` did any optimizations that would allow things to run faster if I put those somewhere else besides the `.zshrc`.

**Comment by Plloi** [comment]
for those to line leaving them them zshrc is likely best.

However depending on how frequently you add/remove node/java envs you could grab static versions of what the lines generate and update as needed.

**Comment by Eriner** [comment]
I understand that most zsh devs (and the documentation) doesn't recommend this, but I suggest putting environment things/heavy stuff like this in your `.zlogin` or `.zprofile`. I keep mine in the latter. This assumes you are starting your X session from a login TTY by running `startx`. The reason is, the exports and env settings will be initialized only once by the login TTY, and subsequent processes will inherent these env vars.

**Comment by akrueger** [comment]
I tried moving those two lines into the `.zprofile` and didn't see much difference. It performs well enough for me, I just didn't want to be leaving anything on the table. Feel free to close--I'm satisfied that those lines just have a cost associated with them.

**Comment by Eriner** [comment]
Fair enough, if the issue persists or becomes a nuisance, feel free to comment again.
