### ISSUE TITLE
[Question] Best way to add a user defined utility function?

### ISSUE THREAD

**Issue by akrueger** [Eriner/zim#122]
Description
-----------
What's the ideal way in Zim for me to add a utility function such as the `take` command from OMZ:

```
function take() {
  mkdir -p $1
  cd $1
}
```

https://github.com/robbyrussell/oh-my-zsh/blob/9dab3c6718d627bc3ea5beb79bfbf0a7f74a7648/lib/functions.zsh

I thought about adding it to the utility module since it's already on the fpath, but if I update Zim, that could cause problems, so perhaps it's better to create a personal file of functions and have it get autoloaded as well as the modules?

Thanks

**Comment by Eriner** [comment]
add it to your `.zshrc`, or create `.zim/modules/custom/functions/take` with the contents of the function you have printed above.

**Comment by akrueger** [comment]
Thanks. Worked great!

**Comment by rea1shane** [comment]
Hi @ericbn 

I think it would be helpful for users to improve the documentation related to customization. When using Oh My Zsh, I can add .zsh files in the custom folder to customize aliases and functions. I would like to know what this corresponds to in Zim.
