### ISSUE TITLE
Question: Use git functions, but not the aliases.

### ISSUE THREAD

**Issue by kaikuehne** [Eriner/zim#123]
Hi, I have my own aliases but would like to use the functions.
For now I have disabled the git module because I cannot work with other's aliases.
But then I don't have the prompt-functions and this really slows things down. I guess it would be faster if the prompt would use the git functions.

Is there a way to opt-out of the aliases / Only enable the functions?
If not, could you add something like this? :)
Thanks!

**Comment by Eriner** [comment]
enable the custom module and symlink `.zim/modules/git/functions/*` to `.zim/modules/custom/functions/*`

**Comment by kaikuehne** [comment]
Thanks!
