### ISSUE TITLE
ZIM breaks $PROMPT variable usage

### ISSUE THREAD

**Issue by bartekrutkowski** [Eriner/zim#126]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:

In a terminal, run `zmanage info` and paste the output below:

```
Zim commit ref:   9f4c21c
Zsh version:      zsh 5.2 (x86_64-apple-darwin16.0)
System info:      Darwin mb.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
```

- gist of .zimrc: stock, no changes
- gist of .zshrc: just few simple exports and functions declarations

Description
-----------

Under oh-my-zsh and zprezto I've very simple things working, that were manipulating $PROMPT variable to indicate various environments states. One of these things was virtualenvwrapper and its `workon env_name` command, that would add '(env_name)' to the $PROMPT, other was my own simple function what would do something like this, when called:
```
export PROMPT_ORIG="$PROMPT"
export PROMPT="[git] $PROMPT_ORIG"
```

None of these things seem to work after switching to ZIM.

Steps to reproduce
------------------
Install virtualenvwrapper, create a new virtualenv, switch to it using `workon` command (prompt should now include the name of the active venv).

**Comment by Eriner** [comment]
Hm, really it should be built into whatever prompt you're using. However, I think you can accomplish what you're looking to do using the `postactivate` file. See: http://unix.stackexchange.com/a/329040.

BTW, if you're using Python3, as of 3.6, it has a new way to create venvs easily: `python3 -m venv ./venv`, if you didn't know; I learned that recently.

**Comment by bartekrutkowski** [comment]
@Eriner Regardless `postactivate` or not (which is, by the way, doing almost the same thing in the link you've pasted) this should simply work, just as it does with stock ZSH, Oh-My-ZSH and zprezto, but, for whatever reason, doesn't work with any Zim prompt/theme.

**Comment by Eriner** [comment]
Yes, as I mentioned above:

> really it should be built into whatever prompt you're using.

**Comment by bartekrutkowski** [comment]
@Eriner I am not sure I understand what are you trying to say here. It's not like ZSH/Bash/Oh-my-zsh/zprezto have any 'special' support builtin for virtualenvwrapper or my own simple functions manipulating $PROMPT - these things should Just Work(™), as shown in the example of my issue report. Question is, why these things are broken when using zim?

Consider this in zprezto:
```
~ ❯❯❯ export PROMPT_ORIG="$PROMPT"
~ ❯❯❯ export PROMPT="[git] $PROMPT_ORIG"
[git] ~ ❯❯❯
```
The same thing doesn't work with zim in eriner, gitster, lean...

**Comment by Eriner** [comment]
It behaves that way because of the prompt. The setting of `${PROMPT}`, at least in the eriner theme, is part of the `prompt_eriner_precmd` function, added using `add-zsh-hook precmd prompt_eriner_precmd`. Like I said, the correct way to resolve your problem would be to add this functionality to the prompt that you are using directly, as opposed to attempting to override `${PROMPT}` in your .zshrc.

**Comment by AfzalivE** [comment]
Backwards compatibility is an important thing though

**Comment by Eriner** [comment]
If this functionality had worked in zim in the past, and suddenly broke in a recent commit, that argument may hold water. However, there is no baseline, so saying it's breaking "backwards compatibility" doesn't mean anything.

**Comment by AfzalivE** [comment]
Sorry, I meant backwards compatibility with the original repo (prezto), I understand though.

**Comment by Eriner** [comment]
The issue as I understand it is, @bartekrutkowski wants to add some (ambiguous) prompt functionality.

The "direct" solution for @bartekrutkowski here is clear: fork a theme and apply whatever custom "hooks" (as you described in the OP) you want.
