### ISSUE TITLE
git-info: bad math expression: illegal character: {

### ISSUE THREAD

**Issue by Tmplt** [Eriner/zim#129]
```
Zim commit ref:   2c0cc6f
Zsh version:      zsh 5.3.1 (x86_64-unknown-linux-gnu)
System info:      Linux temeraire 4.8.13-1-vfio #1 SMP PREEMPT Sat Dec 10 14:26:25 CET 2016 x86_64 GNU/Linux
```

- gist of .zimrc: https://github.com/Tmplt/dotfiles/blob/master/zsh/.zimrc
- gist of .zshrc: https://github.com/Tmplt/dotfiles/blob/master/zsh/.zshrc

Description
-----------
Looking through the commit log the themes `magicmace` and `gitster` have been changed to use the new `git-info` module. Using any of these prompts prints a zsh error:

```
zsh: bad math expression: illegal character: {
```
respectively (when using `gitster`):
```
zsh: bad math expression: operator expected at `(prompt_gi...'
```
Omitting `${(e)git_info[prompt]}` from `magcimace`'s `PROMPT` makes the prompt work (without git info, course).

Steps to reproduce
------------------
`zmanage update && prompt -p magicmace`

**Comment by Eriner** [comment]
> Looking through the commit log the themes `magicmace` and` gitster` have been changed to use the new git-info module.

Enable the `git-info` module in your `zmodules` array inside `.zshrc`. Boom, solved!~
