### ISSUE TITLE
No matches found: .zcomp^(*.zwc)(.)

### ISSUE THREAD

**Issue by ishitatsuyuki** [Eriner/zim#131]
In a terminal, run `zmanage info` and paste the output below:

```
Zim commit ref:   cc34e3f
Zsh version:      zsh 5.3 (aarch64-unknown-linux-android)
System info:      Linux localhost 3.18.22+ #1 SMP PREEMPT Fri Dec 9 18:59:01 CST 2016 aarch64 Android
```

Description
-----------
zlogin tries to glob zcomp\* and it fails with no occurrences.
```
/data/data/com.termux/files/home/.zlogin:24: no matches found: /data/data/com.termux/files/home/.zcomp^(*.zwc)(.)
```

Asynchronous compiling twice is also bad anyway:
https://github.com/Eriner/zim/blob/master/modules/completion/init.zsh#L24
https://github.com/Eriner/zim/blob/master/templates/zlogin#L24

Steps to reproduce
------------------
Maybe a race, maybe a false assumption. Reproduced on fresh termux install, and reproduced by an Arch user installing globally.

**Comment by ishitatsuyuki** [comment]
This seems to be different from the Arch case. It simply fails on termux, possibly due to zsh globbing fails on the Android permission model.

**Comment by Eriner** [comment]
`source .zlogin` to remedy the problem, beyond that I'm not sure. Please post any details or additional information you discover.

**Comment by Eriner** [comment]
Unless there's any new information that indicates this is an issue with zim specifically, I'm going to go ahead and close this issue.

**Comment by chetgurevitch** [comment]
@Eriner It seems like this issue only occurs when trying to source .zlogin if the cache hasn't been built, so during installation or directly after running `zmanage clean-cache.` Opening a new terminal as suggested in the installation instructions resolves it. I guess a catch could be added for that error to instruct the user to open a new terminal but I think it's fine as is.

For the record I'm also running arch but I think that's probably coincidental.

**Comment by chetgurevitch** [comment]
@Eriner This is the result of sourcing .zlogin before the cache has been built in init.zsh, so either during installation or directly after running zmanage clean-cache. Opening a new terminal as instructed fixes it. I guess the message printed could state explicitly that you must open a new terminal and the build-cache command won't work until you do.

For the record I'm also using arch linux but I think it's coincidental.
