### ISSUE TITLE
Tabbing removes lines upwards

### ISSUE THREAD

**Issue by sQVe** [Eriner/zim#134]
_First and foremost - thanks for developing a speedy zsh framework!_

I'm using the Arch AUR build **zsh-zim-git**, currently versioned `r269.61ff601-1`. I'm also currently running **zsh 5.3.1**.

*zimrc:* https://github.com/sQVe/susuwatari-dotfiles/blob/master/zimrc
*zshrc:* https://github.com/sQVe/susuwatari-dotfiles/blob/master/zshrc

Description
-----------
I've had this annoying problem for quite some time that I've been struggling with. When pressing <Tab> when trying to complete something that has **no matches** it will erase and move up one line in my terminal each time I press <Tab>.

Steps to reproduce
------------------

Type `idonotexist` and then <Tab> to try to complete it by pressing <Tab>.

Images or other information
---------------------------
![screenfetch-2017-01-23_22-26-32](https://cloud.githubusercontent.com/assets/2284724/22223464/62b05d64-e1bb-11e6-8383-af678fbc8a70.png)
![screenfetch-2017-01-23_22-26-48](https://cloud.githubusercontent.com/assets/2284724/22223463/62a5f4aa-e1bb-11e6-8cbf-e12362b07fed.png)

**Comment by qifei9** [comment]
I found this issue is related to the `input` module. This could be temporarily fixed by disabling the `input` module or comment several lines out in the `modules/input/init.zsh`:
```
# Redisplay after completing, and avoid blank prompt after <Tab><Tab><Ctrl-C>
expand-or-complete-with-redisplay() {
  print -n '...'
  zle expand-or-complete
  zle redisplay
}
zle -N expand-or-complete-with-redisplay
bindkey "${key_info[Control]}I" expand-or-complete-with-redisplay
```

**Comment by qifei9** [comment]
This issue only appears when I use multi-line prompt. For single-line prompt, it is fine.

**Comment by sQVe** [comment]
@qifei9 What do you mean by multi-line prompt? I'm a bit confused. What's the difference?

**Comment by qifei9** [comment]
@sQVe See: https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#double-lined-prompt

**Comment by Eriner** [comment]
ping @ericbn, my guess is this issue was introduced in #89. Happen to have any suggestions? I don't have time to investigate this right now, but hopefully someone can narrow down the issue a bit further. I can reproduce this bug, and as stated above, it seems to only impact multi-line prompts. Test with `steeef` prompt to reproduce.

**Comment by ericbn** [comment]
@Eriner, I was able to reproduce it with `prompt steeef`. The code I added was trying to fix https://github.com/Eriner/zim/issues/85, but it introduced this other issue.

**Comment by ericbn** [comment]
Same issue reported for Prezto at https://github.com/sorin-ionescu/prezto/issues/1245

**Comment by ericbn** [comment]
Quoting @hotpxl in  sorin-ionescu/prezto#1245:

> Following up on this issue.
The latest ZSH master branch fixed this issue. I believe it is commit `34656ec2f00d6669cef56afdbffdd90639d7b465` that fixed this issue but I have not verified this. So wait for the next ZSH release `5.3.2` and everything will be fine!

**Comment by Eriner** [comment]
Fantastic, thanks @ericbn. Glad to see this tidied up nicely upstream :+1:

**Comment by sQVe** [comment]
@ericbn @Eriner Great to hear. Cheers for investigating. I'll close the issue as soon as I can verify that `5.3.2` fixes it. :+1:

**Comment by sQVe** [comment]
Just making a note that I've not dropped the ball on this one and that I'll close it as soon as I have tested it on the new `zsh` version. It's taking quite some time it seems.

**Comment by naibaf0** [comment]
zsh 5.4.1 has been released. 
Tab completion with multiline prompts seems to work again as it should (I tried steeef and pure)

**Comment by davidzhuo1** [comment]
With zsh 5.4.2 on macOS 10.13.3, it seems like terminal text is still getting consumed with autocomplete.

I took qifei9's observation and removed 'input' from my modules and the problem disappeared

**Comment by ericbn** [comment]
@davidzhuo1, please check #256.
