### ISSUE TITLE
`grc` alias from git module conflicts in name with grc, the "Generic Colouriser"

### ISSUE THREAD

**Issue by helkaluin** [Eriner/zim#139]
As titled.

Especially surprising when you have multiple commands aliased to become `grc $COMMAND` and then having the shell throw fatal errors about "Not a git repository" at you when all you're trying to do is grep the output of ps.

**Comment by Eriner** [comment]
To resolve the issue, you can `unalias grc` in your `.zshrc` after sourcing zim. Alternatively, predicate it with a `\` when invoking the command to use the binary instead of the alias, ex:

`$ \grc` == `$ /usr/bin/grc` (or whatever the actual binary path is)

**Comment by helkaluin** [comment]
I know how to unalias stuff in zsh.  I'm just posting this since it's bad practice to have defaults (Zim currently ships with the Git module enabled by default) that causes namespace conflicts.

**Comment by Eriner** [comment]
There will always be occasional conflicts; just deal with it when it occurs. Changing the structure of zim (or not providing an alias because someone, somewhere, at some point MAY have a conflict isn't a good practice.
