### ISSUE TITLE
git-info: commit_formatted and position_formatted are never set

### ISSUE THREAD

**Issue by lyeoh** [Eriner/zim#143]
It seems that the else statement here https://github.com/Eriner/zim/blob/7d952adf2b58195312593c7f94c610bf7a7daf49/modules/git-info/init.zsh#L196 ensures that the variables `commit_formatted` and `position_formatted` are never set while inside a git repository.

I discovered this while using the gitster theme with an empty .zshrc.

Unless I'm misunderstanding the purpose of the commit hash, I propose removing the else statement entirely.

**Comment by ericbn** [comment]
The `commit_formatted` and `position_formatted` are only set if you're in "detached HEAD" state. The README.md for this module should be making this clear.

This is so you can define the prompt keys as, for example:
```
zstyle ':zim:git-info:keys' format \
  'prompt'  '%b%c'
```
and get either the branch name (from `branch_formatted `, when branch is checked out) or the commit hash (from `commit_formatted`, when "detached HEAD" is checked out). This removes the need for a `coalesce()` function as Prezto had.

**Comment by ericbn** [comment]
If you're not sure what "detached HEAD" state means, check https://www.git-tower.com/learn/git/faq/detached-head-when-checkout-commit

**Comment by lyeoh** [comment]
Thanks for explaining the intended usage.
