### ISSUE TITLE
Error: zsh: bad math expression: operator expected at `(prompt_gi...'

### ISSUE THREAD

**Issue by jeremyvdw** [Eriner/zim#144]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:

In a terminal, run `zmanage info` and paste the output below:

```
- Zim commit ref: 7d952ad
- Zsh version: zsh 5.3.1 (x86_64-apple-darwin16.3.0)
- Operating System Info: Darwin Jenss-iPhone 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
```

- gist of .zimrc: https://gist.github.com/jeremyvdw/8531ac5b07d28d175a005ba18d576e03
- gist of .zshrc: https://gist.github.com/jeremyvdw/2cd1ef3e05e40a27d19db1612d9e1e99

Description
-----------
Drops errors when spawning a new shell:
```
zsh: bad math expression: operator expected at `(prompt_gi...'

_zsh_highlight_widget_reset-prompt: bad math expression: operator expected at `(prompt_gi...'
```

Steps to reproduce
------------------
use any other theme than minimal

Images or other information
---------------------------

**Comment by ericbn** [comment]
You need to include the `git-info` module in your .zimrc zmodules list. This should solve the issue. Now, I agree we should add this to the gitster theme as a comment, and that it should not fail like that if the module is not enabled.

**Comment by jeremyvdw** [comment]
ok, it works.
I believe this was a bug since your [PR](https://github.com/Eriner/zim/pull/124) removed the `git_prompt_info` fn and I must have missed the git_info module.
Thanks Eric!
