### ISSUE TITLE
Recommended customization path

### ISSUE THREAD

**Issue by ryanwood** [Eriner/zim#147]
This is more of a question. It would be great to see more in the docs about the recommended customization path. Coming from oh-my-zsh there are a number of plugins that I want/need to port over to modules for zim. Is it recommended to fork the project and simply maintain a customized version of zim or is there a better way to keep up with updates but customize it?

Thanks and great work!

**Comment by Eriner** [comment]
You can either source the modules from your .zshrc (after zim is sourced) or add them to your local copy of zim. Because it will be a 'new' module that won't conflict with upstream, you shouldn't have any merge conflicts, so it should be easy to work with.
