### ISSUE TITLE
Feature request: auto start Tmux

### ISSUE THREAD

**Issue by irliao** [Eriner/zim#149]
Can you add a Tmux module to auto launch Tmux at startup like this one: https://github.com/sorin-ionescu/prezto/tree/master/modules/tmux ?

**Comment by ericbn** [comment]
The auto launch code from Prezto that is mentioned does not work in MacOS, as discussed in https://github.com/sorin-ionescu/prezto/issues/62.

**Comment by Eriner** [comment]
I'm also okay without adding this functionality.

**Comment by irliao** [comment]
Got it, thank you guys for resolving my issue with an explanation!
