### ISSUE TITLE
How can I add a custom module?

### ISSUE THREAD

**Issue by chrissound** [Eriner/zim#154]
I've copied over https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/z/z.sh to `.zim/modules/z/init.sh`, added `z` to my zmodules in `~/.zimrc`:
I also did `chmod +x .zim/modules/z/init.sh`

```
zmodules=(directory environment git history input utility meta custom \
          syntax-highlighting history-substring-search prompt completion z)
```

I've cleared the cache by: `zsh ~/.zim/tools/zim_clean_cache`, and upon login I still get the following:
```z                               
zsh: command not found: z
```

**Comment by ericbn** [comment]
@chrissound, Zim looks for `"${ZIM}/modules/${module_in_zmodules}/init.zsh"`, so you got the wrong file extensions there. Must be .zsh instead of .sh.
