### ISSUE TITLE
git-info depends on git module

### ISSUE THREAD

**Issue by escobera** [Eriner/zim#161]
I'd like to use the `git-info` module without the git aliases provided by the `git` module, but if I try disabling `git` zim tells me `git-info:9: command not found: is-true`.

I found that `is-true` is defined inside the `git` module, so it is a dependency to `git-info`.

Shouldn't this definition be higher up the chain so these modules are decoupled?

**Comment by ericbn** [comment]
@escobera, very nice catch! It's fixed now.

**Comment by escobera** [comment]
@ericbn is-true is gone but git-info still relies on git for `git-dir` here:
https://github.com/Eriner/zim/blob/9de30b97b10a2a6493956fabeb9578e74e59e525/modules/git-info/init.zsh#L9

**Comment by ericbn** [comment]
@escobera, I missed testing it without having the `git` module on. Should be good now.
