### ISSUE TITLE
after zmanage update, no longer see git info

### ISSUE THREAD

**Issue by wonbyte** [Eriner/zim#166]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:

In a terminal, run `zmanage info` and paste the output below:

```
$ zmanage info
Zim commit ref:   3c2730d
Zsh version:      zsh 5.3.1 (x86_64-apple-darwin16.3.0)
System info:      Darwin Gregs-MacBook-Pro.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
```

- gist of .zimrc: https://gist.github.com/wonbyte/d56864d522b97bf332989f2f77231b2c
- gist of .zshrc: https://gist.github.com/wonbyte/1b5729d8a55dd05735365fdd8d66fa37

Description
-----------
Just used zmanage update to get the latest code and now I no longer receive any git info inside directories.

Steps to reproduce
------------------
zmanage update

Images or other information
---------------------------

<img width="1440" alt="screen shot 2017-04-15 at 9 18 45 pm" src="https://cloud.githubusercontent.com/assets/681965/25068195/2526af1a-2221-11e7-89d4-1a0cd4f3bf6a.png">

**Comment by Eriner** [comment]
Add the `git-info` module to your `zmodules` array.
