### ISSUE TITLE
How to enable git-flow completion (zsh-completion)  in zim?

### ISSUE THREAD

**Issue by supirman** [Eriner/zim#167]
`zmanage info` output :

```
Zim commit ref:   3c2730d
Zsh version:      zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
System info:      Linux sudoman 4.8.0-46-generic #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

- gist of .zimrc: https://gist.github.com/supirman/3f5b00571e031de10c36e9c545de0b33#file-zimrc
- gist of .zshrc: https://gist.github.com/supirman/3f5b00571e031de10c36e9c545de0b33#file-zshrc

Description
-----------
I try to use git flow completion with zim. It already include inside completion. But I have no luck to make it works. Do I need other configuration to make it works?

Steps to reproduce
------------------
1. Enable completion in .zimrc 
2. Type "git flow "
3. Press Tab, regular directory completion will shown

**Comment by supirman** [comment]
It seem manually run `autoload -U compinit && compinit` make the completion works

**Comment by ericbn** [comment]
Cannot reproduce. I'm using:

```
Zim commit ref:   dca1803
Zsh version:      zsh 5.3.1 (x86_64-apple-darwin15.6.0)
System info:      Darwin ericsmacbookpro.local 15.6.0 Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64 x86_64
```
