### ISSUE TITLE
Add help function explaining Eriner theme required font

### ISSUE THREAD

**Issue by sabrehagen** [Eriner/zim#169]
Hi,

Using the `eriner` theme my prompt looks like this:

![image](https://cloud.githubusercontent.com/assets/1094600/25319427/49261b00-28e1-11e7-9014-7fe6915157b8.png)

The glyphs suggest the required font is not installed. What font is required for the eriner theme?

**Comment by Eriner** [comment]
https://github.com/Eriner/zim/blob/master/modules/prompt/themes/eriner.zsh-theme#L6

**Comment by sabrehagen** [comment]
I would add this to the wiki, but I don't know your conventions for where to place it. Definitely would be helpful for newcomers.

**Comment by sabrehagen** [comment]
Running the following commands has me in the same state. Is there any other debug information I can provide?

```
wget https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf
wget https://github.com/Lokaltog/powerline/raw/develop/font/10-powerline-symbols.conf
sudo mv PowerlineSymbols.otf /usr/share/fonts/
sudo fc-cache -vf
sudo mv 10-powerline-symbols.conf /etc/fonts/conf.d/
```

**Comment by Plloi** [comment]
What  font are you presently using?
And have you verified that it's covered in that font config?

**Comment by Tuurlijk** [comment]
Prompt could use a help function explaining the font requirement

```zsh
prompt_eriner_help () {
	cat <<EOH
	This prompt works best with a font containing powerline characters.
	Such a font can be found here: ...... etc.
EOH
}
```

**Comment by Eriner** [comment]
FWIW, if you've stumbled on this issue and want an easy fix, you can install `powerline-fonts-git` from the AUR to resolve the immediate issue.
