### ISSUE TITLE
Don't overwrite grep colours

### ISSUE THREAD

**Issue by nunocastromartins** [Eriner/zim#175]
`grep` colours seem to be hard coded [here](https://github.com/Eriner/zim/blob/master/modules/utility/init.zsh#L39-L40).

The default colours look bad with my colour scheme.
I may be wrong, but `.zshenv` seems like the _proper_ place to set `GREP_COLORS`.
However, it is sourced before Zim loads, making Zim overwrite my settings.

As a result, I'm currently setting `GREP_COLORS` in `.zshrc`, to overwrite Zim.
Once again, correct me if I'm wrong, but I believe that I shouldn't _have_ to set the variable in `.zshrc`.
Would it be possible for Zim not to set the variable if it is already defined, making it possible to set `GREP_COLORS` in `.zshenv`?

I'm not very fluent in bash, but would something like this do the trick?
```bash
DEFAULT_COLOR='37;45'
export GREP_COLOR=${GREP_COLOR:-"${DEFAULT_COLOR}"}   #BSD
export GREP_COLORS=${GREP_COLORS:-"mt=${GREP_COLOR}"} #GNU
```

Another option would be to allow users to specify the colours in `.zimrc`.

What are your thoughts on this?
Thank you for your work so far!

**Comment by Tuurlijk** [comment]
Same goes for other exports in all modules.

Something like this should fix it for the `utility` module.
```
  if [ -z $GREP_COLOR ]; then
    export GREP_COLOR='37;45'             #BSD
  fi
  if [ -z $GREP_COLORS ]; then
    export GREP_COLORS="mt=${GREP_COLOR}" #GNU
  fi
```
