### ISSUE TITLE
git-info ahead/behind is broken

### ISSUE THREAD

**Issue by Tuurlijk** [Eriner/zim#176]
```
Zim commit ref:   a7e060a
Zsh version:      zsh 5.0.8 (x86_64-apple-darwin15.0)
System info:      Darwin Food.local 15.6.0 Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64 x86_64
```

- gist of .zimrc:
https://github.com/Tuurlijk/vim-config/blob/master/.zimrc

- gist of .zshrc:
https://github.com/Tuurlijk/vim-config/blob/master/.zshrc

Description
-----------
When building a promt that accepts colours (like the fire prompt), I noticed that ahead/behind info in the git-info module returned incorrect results

Steps to reproduce
------------------
Enable a prompt with git-info e.g. eriner with the config:

```
	zstyle ':zim:git-info:ahead' format '↑%A'
	zstyle ':zim:git-info:behind' format '↓%B'
	zstyle ':zim:git-info:keys' format \
		'prompt' '%b%c%s%A%B %C%D'
```

Images or other information
---------------------------
On a branch that is behind you will see:
![schermafbeelding 2017-05-09 om 23 18 26](https://cloud.githubusercontent.com/assets/790979/25873216/eafbbc04-350d-11e7-9307-7f8c15ff1b87.png)
Where you should see:
![schermafbeelding 2017-05-09 om 23 18 48](https://cloud.githubusercontent.com/assets/790979/25873221/f127e8be-350d-11e7-9e96-85a5fef584e0.png)

**Comment by ericbn** [comment]
Can you reproduce this with `magicmace` or `minimal` prompt themes?

**Comment by ericbn** [comment]
I'm unable to reproduce this using any of the existing Zim prompts, not by making the changes in eriner as per "Steps to reproduce above". I always get the `↓n` to show in the prompt...

**Comment by Tuurlijk** [comment]
![magicmace](https://cloud.githubusercontent.com/assets/790979/26032701/c8c98de8-3899-11e7-836a-f0454115b4eb.png)
![pure](https://cloud.githubusercontent.com/assets/790979/26032702/cc9c8ea2-3899-11e7-96e4-afeb5c5279f6.png)

**Comment by ericbn** [comment]
I'm unable to reproduce.

<img width="570" alt="screen shot 2017-05-18 at 9 02 24 pm" src="https://cloud.githubusercontent.com/assets/4120606/26230355/d7c8bd6a-3c0d-11e7-9464-81b4b6222449.png">

These are changes made to eriner:
```
--- a/modules/prompt/themes/eriner.zsh-theme
+++ b/modules/prompt/themes/eriner.zsh-theme
@@ -98,8 +98,10 @@ prompt_eriner_setup() {
   zstyle ':zim:git-info:action' format ' (%s)'
   zstyle ':zim:git-info:clean' format 'green'
   zstyle ':zim:git-info:dirty' format 'yellow'
+  zstyle ':zim:git-info:ahead' format '↑%A'
+  zstyle ':zim:git-info:behind' format '↓%B'
   zstyle ':zim:git-info:keys' format \
-    'prompt' '%b%c%s' \
+    'prompt' '%b%c%s %A%B' \
     'color' '%C%D'
```

I'm using `zsh 5.3.1` on `Darwin 15.6.0`.

**Comment by ericbn** [comment]
Got it. Reverted to `zsh 5.0.8` and I'm seeing the issue now.

**Comment by ericbn** [comment]
@Tuurlijk, started new unsupported `zsh-5.0` branch at 12e4ee2 that also contains the fix to this issue.
