### ISSUE TITLE
Prompt init does not accept prompt parameters

### ISSUE THREAD

**Issue by Tuurlijk** [Eriner/zim#178]
```
Zim commit ref:   a7e060a
Zsh version:      zsh 5.0.8 (x86_64-apple-darwin15.0)
System info:      Darwin Food.local 15.6.0 Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64 x86_64
```

- gist of .zimrc:
https://github.com/Tuurlijk/vim-config/blob/master/.zimrc

- gist of .zshrc:
https://github.com/Tuurlijk/vim-config/blob/master/.zshrc

Description
-----------
When building a promt that accepts colours (like the fire prompt), I noticed that prompt init does not accept the colour parameters.

Steps to reproduce
------------------
Add a prompt with parameters to your `.zimrc`
```
zprompt_theme="fire 23 124 208"
```

Images or other information
---------------------------
Expected:
![schermafbeelding 2017-05-09 om 23 27 41](https://cloud.githubusercontent.com/assets/790979/25873536/3acb6d28-350f-11e7-8236-cdb962b8500d.png)

Actual:
![schermafbeelding 2017-05-09 om 23 28 15](https://cloud.githubusercontent.com/assets/790979/25873542/41c530b4-350f-11e7-95b4-474e94b89a2b.png)

**Comment by Eriner** [comment]
Thanks, should be fixed in the commit above!
