### ISSUE TITLE
Parse error near ']]'

### ISSUE THREAD

**Issue by SethDusek** [Eriner/zim#18]
/home/kamal/.zim/modules/prompt/init.zsh:5: parse error near `]]'

This is what I get when I put source .zim/init.zsh in my .zshrc

**Comment by Eriner** [comment]
What version of zsh are you using? You can check with `zsh --version`. If you change the second part of the conditional on that line from `[[ ${zprompt_theme} ]]` to `(( ${+zprompt_theme} ))`, does that fix the problem?

**Comment by SethDusek** [comment]
zsh 5.0.2 and yes that fixed it, thanks
