### ISSUE TITLE
Deprecate support for zsh versions < 5.2

### ISSUE THREAD

**Issue by ericbn** [Eriner/zim#184]
As discussed in #177, and as per [last Eriner's comment](https://github.com/Eriner/zim/pull/177#issuecomment-302901655):

> I would suggest we deprecate support for < 5.3 in the init file now, and in two weeks on June 3rd, we will begin allowing/merging breaking changes for < 5.3.
>
> The majority of users should already be on a current version of zsh, but if they aren't, two weeks is plenty of time of advance notice. After that, we will return 1 on zsh != latest minor patch and merge breaking changes. Any issues with this?

**Comment by lnicola** [comment]
One reason to support older versions of `zsh` would be the fact that `5.3` is pretty rare. CentOS 7 has `zsh 5.0` and `zim` already has issues with that (the `eriner` prompt no longer works, for example).

In the case of CentOS, there is a third-party repository with `zsh 5.1`, but I don't see myself upgrading to a newer version.

**Comment by Eriner** [comment]
That means CentOS 7 matches approximate versions with Apple and Debian-stable - par for the course. Again, this is an upstream packaging issue. Some distros like CentOS and Debian-stable only maintain the most stable, vintage, and beautifully-aged packages to remove the burden of having to run modern software from their users. Maintaining full compatibility with these distros, working around code changes that were made over a year ago, is an necessary burden on developers. It makes sense in a server environment where stability is king, but who is installing zim on such a system? 

I'd be willing to create a branch of zim as it is now to maintain the old version, but no additional feature changes will be committed to support these old versions, and master will only support zsh >= 5.3.
We can prompt users to switch to this branch if zsh < 5.3.

If anyone wants to change nothing and have zim work with *-stable zsh packages, we'll have them pull from "legacy-5.0" branch.
For the rest (and target group) who want to have updated, current code, they'll pull master and either `make install` or install the relevant package to get a version of zsh that's been compiled within the last 365 days.

**Comment by ericbn** [comment]
@Eriner, maybe we are restricting Zim to ArchLinux and MacOS users with this... (which we both are fine with, of course.)

And won't maintaining a separate "legacy-5.0" branch together with a master, for zsh latest version, be more work than just maintaining one branch? Also not sure this is desired for the future plans on the zimframework organization, as that would mean maintaining those branches for each separate module.

**Comment by Eriner** [comment]
@ericbn it won't be more work because we'll branch for `legacy` now, then it won't ever be touched unless there's some breaking issue that's an easy fix. zimframework organization will be latest minor only, as we've discussed in other threads.

**Comment by Eriner** [comment]
@ericbn Also,
> maybe we are restricting Zim to ArchLinux and MacOS users with this... (which we both are fine with, of course.)

Not exactly; we're dropping support for distros/OS' that don't keep up-to-date packages, but even then it's not the distros that we have issue with. Users of these distros can update their packages manually, create their own package, or manage their own version of zsh in `/usr/local/bin` or their own `${HOME}/.bin/` folder -- that's up to the user, as based on their OS they've elected to only run old packages. 

Case in point, Debian stable support is effectively dropped, but people can always install from backports or use [unstable](https://packages.debian.org/unstable/shells/zsh) or [testing](https://packages.debian.org/testing/shells/zsh). We're not restricting Zim to only Arch and Mac, we just require up-to-date packages. :)

**Comment by ericbn** [comment]
> it won't be more work because we'll branch for legacy now, then it won't ever be touched unless there's some breaking issue that's an easy fix.

Okay, hope we don't need to go back there very often. And looks like `zmanage` would work as expected when in another branch.

>  We're not restricting Zim to only Arch and Mac, we just require up-to-date packages. :)

Cool. I'm trying to play a little bit of "devil's advocate" here...  :- )  And I remember how boring it was to build zsh from source in CentOS, as even some dependencies had to be build from source too, to be able to have the latest versions.

**Comment by jorvi** [comment]
Fully agree with @lnicola. My guess is that (by virtue of most developers having a Mac and running macOS) your biggest group of users will have to either have a 'soft' dependency in `brew` or will have to manually manage their zsh binary. The majority of your users (macOS+those on versioned release Linux) isn't on a current zsh, but on 5.2 or older. I get that it sucks to have to target older versions as the minimum supported version, but that's what's most user friendly for your userbase.

May I offer an alternative: you support the major ZSH release that's closest to 3 years old as the minimum. Currently, that's [5.1](http://zsh.sourceforge.net/News/). In December, you can drop support for 5.1 and you support 5.2 as the minimum version. A year after that, you drop support for 5.2 and target 5.3 as the minimum. This means you won't have to be endlessly backwards compatible, but you don't leave people on versioned releases (or those who have machines with a slow upgrade cycle) out in the cold.

**Comment by Eriner** [comment]
@jorvi so we support legacy software that's over 3 years old? That's silly. Yes, it sucks that Apple doesn't maintain up-to-date packages, but that's their choice.

> This means you won't have to be endlessly backwards compatible, but you don't leave people on versioned releases (or those who have machines with a slow upgrade cycle) out in the cold.

Three years is pretty much "endlessly" backwards compatable. Three years is a long damn time. If OS' can't keep packages within a year, they're boning something up, and we shouldn't be punished for it.

**Comment by Eriner** [comment]
Also, to tie into #182, we can prompt the user to upgrade (handled by said script) via `brew` if the Mac issue is an issue. Like I mentioned in that issue thread, checking for the version of zsh is relatively easy.

**Comment by lnicola** [comment]
> If OS' can't keep packages within a year, they're boning something up, and we shouldn't be punished for it.

It's not that they can't keep up, it's that there's no need to. My example was CentOS 7, which was released in 2014 and is supported until 2024. Fedora 25 and Ubuntu 17.04 have zsh 5.2. Sure it's easy to update on a rolling distribution or Mac OS, but other users are stuck with the older versions.

> and we shouldn't be punished for it.
But then you're punishing the users who don't or can't run Arch Linux.

**Comment by Eriner** [comment]
Handling the upgrade via the script; is that "punishing the users"?

**Comment by PatTheMav** [comment]
> Handling the upgrade via the script; is that "punishing the users"?

Well, that's not possible if you `ssh` onto remote machines controlled by IT departments (which, for obvious reasons, favour stability over "bleeding edge" versions) but still want aim to improve your everyday shell experience.

In that case it might come down to explicitly stating that zim is primarily meant for local shell use, with the legacy version supporting "stable" systems.

(Or how about a zim for "remote" systems with a smaller feature set and more lenient version requirements).

**Comment by Eriner** [comment]
> Well, that's not possible if you ssh onto remote machines controlled by IT departments

Zim was never really made for this use case (managed servers vs personal/dev machines).

Like I've said elsewhere in these threads, we'll branch off a legacy version (current master) and not make backward-incompatible breaking changes. Install script could even switch branches and re-run if not `is-at-least`.

**Comment by ericbn** [comment]
@Eriner, I think the reason there are some many tools like Zim (and Prezto, and Oh-My-Zsh, and Zplug, and...) for Zsh is a reflection of how unfriendly Zsh is out-of-the-box. And the fact that there are older versions of Zsh running on latest OSs is just another ingredient on that Zsh user experience.

I believe we should keep Zim:
1. Simple for users
2. Simple on it's own implementation

We're already supporting Zsh >= 5.0 unless for the https://github.com/Eriner/zim/pull/177#issuecomment-302700272 issue reported earlier. Maybe there are another issues around that would need another 1-or-2-line fixes, but it wouldn't get more complex that what we already have. And looking at the current code, supporting Zsh >= 5.0 does not look that bad from the item 2 (on the list above) perspective. But it brings a good feature for item 1. As @jorvi said, it basically enables ~90% of the users to use Zim without going through the (not simple for them) process of upgrading the Zsh version that came with their OSs. And as a site node, using the two items above as reference, I'd say having a separate branch for legacy is a down for both items.

**Comment by Eriner** [comment]
@jorvi @ericbn @lnicola @PatTheMav 

I'd capitulate with supporting >=5.2, but in that case, I'd like to drop support entirely for <5.2. If the concern is just Mac/Ubuntu/Fedora "default" (read, old) packages, then there's no need to support anything less than 5.2 at all. No legacy branch. I'm still not happy with having to support software that's over a year and a half old, but I can't force upstream distros to update their shit, and I don't want to wreck the installations of most of our users.

The whole point of this is to remove the burden from both developers and users, such that we can expect certain bugs not to exist and we won't have to work around them, and users won't experience weird issues due to legacy zsh versions. 5.2 will give us *most* of that, and is an acceptable compromise.

Any objections to that?

**Comment by jorvi** [comment]
@Eriner, yes, I can happily live with that. Especially because you can just tell complainers 'just upgrade yo shit'. I would be (as you said) for feature-freezing the current state of Zim, and saving that as a legacy branch. I'll put a trigger in the script for `! at-least-version` and it'll switch to the legacy branch if that condition is met. Glad we could find a compromise :)

**Comment by Eriner** [comment]
@jorvi But do we need a legacy branch, or is that just more work and complications for us? Seeing as you've well described, the vast majority have/support 5.2? If we can just tell people "just upgrade yo shit", then why not just hard-fail in the script and tell them that?

**Comment by ericbn** [comment]
@jorvi, I would definitely go for "no legacy branch". @Eriner also agreed with that in his last comment. (So there would be no option for people behind 5.2, which I'm not sure I totally agree with)

**Comment by Eriner** [comment]
@ericbn If we really want, we can do a legacy branch for the people that do need <5.2, but make the managament/use of that **their** problem, and the installation script/we will have nothing to do with any magic surrounding that branch.

I don't have an outright problem with a legacy branch, I just want to make this change a net-gain for us and users, and I'm not sure any additional work/complexity on our end will assist in that.

**Comment by jorvi** [comment]
I think I expressed it wrong.

We'll take the Zim codebase as it is now (+ the install script). We copy it as a legacy branch. We won't offer support on it, we won't update it (pull requests _might_ be accepted if someone is up for it, but this is purely on a voluntary basis). If the script detects zsh < 5.2, it will `git checkout branch legacy`. Meanwhile, everyone  >= 5.2  will be on the master branch, where development continues. This was, you at least offer a crutch to legacy users (with zero involved effort), and can continue development for those that are up-to-date.
Tbh, instead of legacy branch we should just version the legacy branch (so this would be Zim 5.0 or whatever), because at some point in the future, you will have to deprecate zsh 5.2, and then you have two legacy branches. So, in short

* Copy current state of Zim to new branch, name it 5.0; this branch receives no support, is not updated, it is only there for old systems
* Master branch is for everyone on >= 5.2, gets updated
* At some point in the feature, 5.2 gets deprecated. The state of the Master branch then gets copied to branch 5.2; his branch receives no support, is not updated, it is only there for old systems
* etc.

**Comment by ericbn** [comment]
@Eriner, @jorvi, I also like the idea of an "unsupported branch", working more as a versioning system for Zim...

**Comment by lnicola** [comment]
For anyone who cares about this, `zsh 5.2` can be easily built for CentOS 7 with the Fedora 25 SRPM. `5.3` might be available when Fedora 26 comes out.

About `5.1` or `5.0`, I'm not convinced that the maintenance cost of supporting them is that large. I would argue for at least not intentionally breaking it and accepting PRs with compatibility fixes. But this is not my call to make.

**Comment by Eriner** [comment]
@ericbn been >30 days since that commit, think we're ready to drop support for < 5.2?

**Comment by ericbn** [comment]
@Eriner, sure! Let's also create a new branch, from the current commit, called `zsh-5.0`?

**Comment by ericbn** [comment]
Support for versions < 5.2 dropped in master branch at 537f076, and new branch for versions >= 5.0 and < 5.2 started at 12e4ee2.

**Comment by JonathanAnderson** [comment]
Thanks for this. As a member of a research group we and many others are forced to use centos based environments in. Having the `zsh-5.0` branch is super useful until the current version of centos upgrades its zsh. Of the redhat based distros, only fedora users are able to get a zsh > 5.2 out of the box and many of us are at the mercy of a sysadmin who has no interest in supporting a non default shell version in case they accidentally create a back door or something.
