### ISSUE TITLE
How to use this plugin with ZIM?

### ISSUE THREAD

**Issue by jitendravyas** [Eriner/zim#185]
https://github.com/tysonwolker/iterm-tab-colors

**Comment by Brottweiler** [comment]
Use a zsh plugin manager like the [readme suggests](https://github.com/tysonwolker/iterm-tab-colors#installing-with-zplugantigenzgen).

**Comment by Eriner** [comment]
> Use a zsh plugin manager like the readme suggests.

In this case, you could literally just copy-paste the contents of the zsh file into your .zshrc. Or source the file  from your .zshrc.
