### ISSUE TITLE
Regression: Fasd broken on zsh 5.0.8 OSX 10.11.6 since recent commit

### ISSUE THREAD

**Issue by kiryph** [Eriner/zim#186]
Reverting commit https://github.com/Eriner/zim/commit/c58f9015ec4f469fdf269f562d4098e67d7dccf9
resolves my issue:
```
❯ fasd_cd -d
fasd:383: no such file or directory:
```
This commits sounds completely unnecessary anyway.

**Comment by ericbn** [comment]
The changes in that commit could have undesirable effects, as I [mentioned before](https://github.com/Eriner/zim/pull/180#issuecomment-301131889).

@kiryph, thanks for reporting this. Can you please verify if any of those environment variables that appear on that commit are set as empty in your environment?

**Comment by kiryph** [comment]
No, none of them are defined: the command `env` returns:
```
TERM_SESSION_ID=w0t1p0:A4480DE5-2547-4DB3-9BB7-8B8C486BFC85
COLORFGBG=11;15
ITERM_PROFILE=Default
XPC_FLAGS=0x0
PWD=/Users/kiryph
SHELL=/bin/zsh
TERM_PROGRAM_VERSION=3.0.15
TERM_PROGRAM=iTerm.app
TERM=xterm-256color
HOME=/Users/kiryph
TMPDIR=/var/folders/d_/5kjxh9v92k752bvzf559fd3c0000gn/T/
USER=kiryph
XPC_SERVICE_NAME=0
LOGNAME=kiryph
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
ITERM_SESSION_ID=w0t1p0:A4480DE5-2547-4DB3-9BB7-8B8C486BFC85
SHLVL=1
OLDPWD=/Users/kiryph
PAGER=less
LSCOLORS=exfxcxdxbxGxDxabagacad
LS_COLORS=di=34:ln=35:so=32:pi=33:ex=31:bd=36;01:cd=33;01:su=31;40;07:sg=36;40;07:tw=32;40;07:ow=33;40;07:
GREP_COLOR=37;45
GREP_COLORS=mt=37;45
LESS_TERMCAP_mb=
LESS_TERMCAP_md=
LESS_TERMCAP_me=
LESS_TERMCAP_se=
LESS_TERMCAP_so=
LESS_TERMCAP_ue=
LESS_TERMCAP_us=
PROMPT_EOL_MARK=
VISUAL=vim
PYENV_SHELL=zsh
PYENV_VIRTUALENV_INIT=1
XML_CATALOG_FILES=/usr/local/etc/xml/catalog
PERL5LIB=/Users/kiryph/perl5/lib/perl5
PERL_LOCAL_LIB_ROOT=/Users/kiryph/perl5
PERL_MB_OPT=--install_base "/Users/kiryph/perl5"
PERL_MM_OPT=INSTALL_BASE=/Users/kiryph/perl5
ITERM_SHELL_INTEGRATION_INSTALLED=Yes
_=/usr/bin/env
```

**Comment by Eriner** [comment]
The commit is broken, my fault for not reviewing the changes thoroughly enough. 
`(( ! "${+foo}" ))` should be `(( ! ${+foo} ))`. Anything wrapped in curly braces doesn't ever need quotes, and it also breaks the syntax. I'll push a fix to resolve this issue momentarily.

**Comment by Eriner** [comment]
Thanks for the report @kiryph, glad we caught this one quickly.

**Comment by kiryph** [comment]
@Eriner: Thanks for the fix.
