### ISSUE TITLE
No bindkeys configured for standard bash navigation

### ISSUE THREAD

**Issue by chrissound** [Eriner/zim#187]
CTRL-(A/E/U) doesn't seem to be configured?

**Comment by lnicola** [comment]
Actually, these work for me in `zim`, although I wasn't aware that they existed. So thanks for that 👍.

**Comment by chrissound** [comment]
Strange, where are they defined?

**Comment by lnicola** [comment]
No idea, but if I run `bindkey` I get:

```
"^A" beginning-of-line
"^E" end-of-line
"^U" kill-whole-line
```

**Comment by chrissound** [comment]
Why was this closed? What more information do you need?

**Comment by lnicola** [comment]
@chrissound Do you have the `input` module enabled?

**Comment by Eriner** [comment]
It will change these bindings based on your `EDITOR`, and will only have those binds if you're not in `vi` mode. `emacs` mode/bindings is the default.
