### ISSUE TITLE
Directory or executable color completion

### ISSUE THREAD

**Issue by nmccready** [Eriner/zim#188]
For bug reports, please provide the following information:

In a terminal, run `zmanage info` and paste the output below:

```
❯ zmanage info
Zim commit ref:   126e950
Zsh version:      zsh 5.3.1 (x86_64-apple-darwin16.3.0)
System info:      Darwin MAREMIT1032503 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
```

- gist of [.zimrc:](https://gist.github.com/nmccready/38dd31eae0555eb6b4c773d117694413)
- gist of [.zshrc:](https://gist.github.com/nmccready/56e022e94aedf4cfeee1d692d7a3ddd0)

Description
-----------

Wondering what the best way is to set the coloring of directory or executable completion for zim.

Currently a dark theme with dark blue text is not readable.

![screen shot 2017-06-06 at 3 55 10 pm](https://user-images.githubusercontent.com/583593/26849000-82237158-4ad0-11e7-92bb-1569ba92930b.png)

Steps to reproduce
------------------
Tab completion for any nested directory or executable file.

Images or other information
---------------------------

**Comment by nmccready** [comment]
@Eriner

**Comment by nmccready** [comment]
Maybe related https://github.com/Eriner/zim/issues/175

**Comment by Eriner** [comment]
See the variables at the top of [this](https://github.com/Eriner/zim/commit/f15d6e4e0226480f2c9366e0a91c8450532eaf93) commit. Customize and set those in your `.zshrc`. They shouldn't be overridden.

**Comment by nmccready** [comment]
So yes this fixes my COLORS for grep and LS, but is not resolving the color issues with dark blue with directories for tab completion in zim.

```
export CLICOLOR=1
export LSCOLORS=GxFxCxDxHxagadabagacad
export GREP_COLORS='sl=97;48;5;236:cx=37;40:mt=30;48;5;186:fn=38;5;197:ln=38;5;154:bn=38;5;141:se=38;5;81';
export GREP_OPTIONS='--color=always'
export GREP_COLOR='1;35;40'
```
