### ISSUE TITLE
How to enable autosuggestions?

### ISSUE THREAD

**Issue by dstufft** [Eriner/zim#190]
From looking at the zim modules directory, it appears I should be able to enable autosuggestions just by adding ``autosuggestions`` to my ``zmodules`` setting. However this does not appear to actually change any behavior. Do I need to do anything else to enable it?

**Comment by smarquez1** [comment]
You shouldn't need anything else. I just updated zim from an older version using `zmanage update` , added `autosuggestions` to my `zmodules` and opened another session. Works like a charm.

**Comment by dstufft** [comment]
Hmm interesting, it doesn't seem to be working for me. Could you post your entire zmodules?

**Comment by smarquez1** [comment]
Sure:
```
zmodules=(autosuggestions directory environment git git-info history input utility meta custom \
          syntax-highlighting history-substring-search prompt archive \
          completion)
```

**Comment by Brottweiler** [comment]
It was added 2 days ago, you sure you are up to date?

**Comment by dstufft** [comment]
Yea, I wasn't using zim 2 days ago :)

**Comment by dstufft** [comment]
This doesn't appear to be a problem with zim, manually installing zsh-autosuggestions into my .zshrc isn't working either. Closing this.
