### ISSUE TITLE
Bug in the installation instructions

### ISSUE THREAD

**Issue by marin101** [Eriner/zim#193]
I managed to break the installation procedure described on the main page :)

Consider a .zshrc file starting without any newlines (eg. like this):
`export DOTFILES=$HOME/.dotfiles`

Following the installation instructions, after running the code:

```
setopt EXTENDED_GLOB
for template_file ( ${ZDOTDIR:-${HOME}}/.zim/templates/* ); do
  user_file="${ZDOTDIR:-${HOME}}/.${template_file:t}"
  touch ${user_file}
  ( print -rn "$(<${template_file})$(<${user_file})" >! ${user_file} ) 2>/dev/null
done
```

because the process substitution removes the trailing newlines the resulting .zshrc file is (pay attention to the **fiexport**):

```
#
# User configuration sourced by interactive shells
#

# Source zim
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fiexport DOTFILES=$HOME/.dotfiles
```

The best I could do to fix this is to replace:
`( print -rn "$(<${template_file})$(<${user_file})" >! ${user_file} ) 2>/dev/null`

with:
`( print -n "$(<${template_file})\n$(<${user_file})" >! ${user_file} ) 2>/dev/null`

However, it would be better if there was a way to keep all the trailing newlines

**Comment by Eriner** [comment]
Hopefully this will be resolved by https://github.com/Eriner/zim/pull/182

**Comment by ericbn** [comment]
This was already reported in #94
