### ISSUE TITLE
history-substring-search not working

### ISSUE THREAD

**Issue by dsdeiz** [Eriner/zim#197]
```
Zim commit ref:   460090b
Zsh version:      zsh 5.3.1 (x86_64-apple-darwin16.6.0)
System info:      Darwin MacBook-Pro.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
```

`.zimrc` just has this change:

```
zmodules=(directory environment git git-info history input utility meta \
          syntax-highlighting history-substring-search prompt completion fasd custom)
```

No changes in `.zshrc`.

Description
-----------

`history-substring-search` not working. I saw #23. I'm always on `emacs` mode. In my `modules/custom/init.zsh`, I have `bindkey -e`. When I press Up/Down, it doesn't behave like in prezto where it would search the history based on substring. It simply just goes scrolls through the history

Steps to reproduce
------------------

Install `zim`. 
Press Up/Down with a substring that exists in the history.

Images or other information
---------------------------

```
diff --git a/modules/custom/init.zsh b/modules/custom/init.zsh index 57934ad..fdbf7a3 100644 --- a/modules/custom/init.zsh +++ b/modules/custom/init.zsh @@ -5,4 +5,7 @@ # any custom stuff should go here. # ensure that 'custom' exists in the zmodules array in your .zimrc - +bindkey -e +export PYTHONPATH="$(brew --prefix)/lib/python2.7/site-packages:$PYTHONPATH" +export PATH="$HOME/.cargo/bin:$PATH" +source <(gopass completion zsh)
```

**Comment by Eriner** [comment]
What's the output of `echo ${TERM}` ?

**Comment by harmonwood** [comment]
Steps to reproduce:
$> `bindkey -v`
up arrow in both insert and normal mode do not search.

$> `bindkey -e`
up arrow search mode works just fine.
