### ISSUE TITLE
Checking out a new branch in git does not change the prompt

### ISSUE THREAD

**Issue by seagoj** [Eriner/zim#20]
Hello,

I've installed zim and everything is running great with one exception: when I make changes to a git repo that should be reflected in the prompt (change branches, add/rm a file, etc.), it doesn't update until I either move out of the repo and back in or manually run git_prompt_info. I've attached every uncommented line of my .zimrc below. Thanks for taking a look!

    zmodules=(directory environment git ssh history input utility custom spectrum pacman
          syntax-highlighting history-substring-search prompt completion)

    zprompt_theme='steeef'

    highlighting/blob/master/docs/highlighters.md
    zhighlighters=(main brackets cursor)

    zssh_ids=(id_rsa)

    zpacman_frontend='yaourt'
    zpacman_helper=(aur)

**Comment by seagoj** [comment]
Actually, it looks like this bug only shows up when using the steeef theme. I'll poke around and see if I can figure out what the difference is.

**Comment by Eriner** [comment]
The steef theme only changes the prompt upon making a call to git/svn.

**Comment by seagoj** [comment]
Interesting. Checking out a different branch doesn't qualify?

**Comment by Eriner** [comment]
It doesn't have any magic that runs in the background like some of the other themes do. It is more conservative. Typing anything starting with `git` will cause it to change, but using aliases will not. I can change this if it bothers you; it's not a big deal to change.

**Comment by seagoj** [comment]
No, I mean if it's working as intended then no harm, no foul. I migrated from from prezto and noticed the difference and thought it might be a bug. I'll let it ride for a while and see what I think.

Great work by the way! I look forward to using zim.

**Comment by Eriner** [comment]
No problem. Glad you like it!
