### ISSUE TITLE
Make zim folders and rcfiles visible as install option

### ISSUE THREAD

**Issue by voyeg3r** [Eriner/zim#202]
I have been looking into zim config files and all is based in hidden files .zshrc .zlog .zim and so on. 
what happens is that I am using a $DOTFILES that is already hidden, I would like to change this without breaking the configuration. 

I would like this option during installation because I also have my vimfiles in the same folder, and then  create symlinks to my home dir. 

By the way, zim rocks is notably fast. Keep up the good work!

**Comment by Eriner** [comment]
`ln -s ${DOTFILES}/zim/.zshrc ${HOME}/.zshrc`

Would that work?
