### ISSUE TITLE
Tab completion broken for umount with latest zsh version 5.4.1

### ISSUE THREAD

**Issue by protist** [Eriner/zim#204]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:

In a terminal, run `zmanage info` and paste the output below:

```
zsh: command not found: zmanage
```
🤷

- ~/.zimrc: `zmodules=(completion)`
- ~/.zshrc: `source /usr/lib/zim/init.zsh`

Description
-----------
Completion module is broken for umount with zsh 5.4.1. Reverting to the previous zsh 5.3.1 fixes this.

Steps to reproduce
------------------
```
$ umount <tab>
```

Expected output
---------
Completion options, e.g.
```
 -- device label --
binfmt_misc  configfs     dev          fusectl      mqueue       pstore       securityfs   systemd-1  
cgroup       debugfs      devpts       hugetlbfs    proc         run          sys          tmpfs      
 -- device path --
/dev/mapper/luks-<redacted>
/dev/sda2                                            
/dev/sdb5                                            
/dev/sdb6                                            
 -- mount point --
/                                 /run/user/1000                    /sys/fs/cgroup/pids             
/dev                              /run/user/1001                    /sys/fs/cgroup/systemd          
/dev/hugepages                    /sys                              /sys/fs/cgroup/unified          
/dev/mqueue                       /sys/fs/cgroup                    /sys/fs/fuse/connections        
/dev/pts                          /sys/fs/cgroup/blkio              /sys/fs/pstore                  
/dev/shm                          /sys/fs/cgroup/cpu,cpuacct        /sys/kernel/config              
/HDD                              /sys/fs/cgroup/cpuset             /sys/kernel/debug               
/home                             /sys/fs/cgroup/devices            /sys/kernel/security            
/proc                             /sys/fs/cgroup/freezer            /tmp                            
/proc/sys/fs/binfmt_misc          /sys/fs/cgroup/memory             /var/cache                      
/run                              /sys/fs/cgroup/net_cls,net_prio   /var/log                        
/run/media/foo/fooHD              /sys/fs/cgroup/perf_event         /var/tmp                        
```

Observed output
---------------
```
$ umount _mount:934: command not found: _umountable
_mount:934: command not found: _umountable
_mount:934: command not found: _umountable
```

Other information
--------------
I'm running the latest version of zim, i.e. 537f076. I also tried an old version (7d952ad) to see if it were a regression, but it wasn't. Zim just need to be updated to work with the latest zsh version.

**Comment by Plloi** [comment]
Look like your zsh package is missing the _umountable command introduced in 5.4.1
https://github.com/zsh-users/zsh/commit/5654b905f96720bef285dc92d6b2e2cc31bd971e#diff-c5c29f7af2bf5f3da08b9dc134f4ede7

**Comment by protist** [comment]
I'm not exactly sure if this is the same command, but I do have a file provided by my package manager at `/usr/share/zsh/functions/Completion/Unix/_umountable`. (The link mentions `Completion/Unix/Type/_umountable` instead.)

Sorry, I forgot to mention in the initial report: I'm running Arch Linux. I'm not sure if the package manager [changes the path](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/zsh), but it's always worked fine with zim previously.

**Comment by Eriner** [comment]
`rm ${HOME}/.zcompdump* && exec zsh`, then `source .zlogin`.

**Comment by protist** [comment]
Thanks @Eriner, that fixed it. FWIW I only needed the first part; I had no `.zlogin` file.
