### ISSUE TITLE
zcompare:33: defining function based on alias `ls'

### ISSUE THREAD

**Issue by jeffdupont** [Eriner/zim#205]
```
Zim commit ref:   537f076
Zsh version:      zsh 5.4.1 (x86_64-apple-darwin16.7.0)
System info:      Darwin jdupont-retina17 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
```

- gist of .zimrc: https://gist.github.com/jeffdupont/cb32903eb9c043539f7d911b2b4efe05
- gist of .zshrc: https://gist.github.com/jeffdupont/3df54f0c7470d4adfd7cbb1b7d059684

Description
-----------
zcompare:33: defining function based on alias `ls'
zcompare:33: parse error near `()'
zcompare:zcompile:2: can't read file: /Users/jdupont/.zim/modules/syntax-highlighting/external/highlighters/main/test-data/function.zsh

#44 does not solve this.

Commenting out the function.zsh code clears out the messages, but doesn't explain why it started happening. Even after clearing out every single item related to zim and zsh and then reinstalling fresh, the error still appears.

Steps to reproduce
------------------
open a terminal window

Why would this be looking for a file in "test-data". I would think that anything within that directory would be used for testing the module only...

**Comment by ericbn** [comment]
I'm having this exact same issue with zsh 5.4.1 too. Didn't investigate further, as it looks like it's an issue in [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting), since zim is just adding a very simple `init.zsh` on top of it.

**Comment by ericbn** [comment]
Updated the [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting) to the newest `0.6.0` release of it, and this fixes this issue.

@jeffdupont, update your zim (`zmanage update`), clean the caches (`zmanage clean-cache`), restart your shell, and let me know if the issue is gone for you, while still using `zsh 5.4.1`...

**Comment by jeffdupont** [comment]
Still having the same alias issue:

zcompare:33: defining function based on alias `ls'
zcompare:33: parse error near `()'
zcompare:zcompile:2: can't read file:
/Users/jdupont/.zim/modules/syntax-highlighting/external/highlighters/main/test-data/function.zsh

**Comment by ericbn** [comment]
@jeffdupont, you're right. This is not fully fixed yet. Created this upstream PR: https://github.com/zsh-users/zsh-syntax-highlighting/pull/443

**Comment by jeffdupont** [comment]
Thanks, I have it commented out right now and everything seems to be
working fine... awaiting for the final fix so I don't need to remember
which lines to comment out :)

**Comment by ericbn** [comment]
@jeffdupont, there was no upstream fix for this, but rather a fix (that is also an optimization) on our `.zlogin` file. Please check 2a9a003

**Comment by bcatubig** [comment]
@ericbn I'm still seeing this issue even with 2a9a003 fix

```
$ zmanage info
Zim commit ref:   2a9a003
Zsh version:      zsh 5.4.1 (x86_64-apple-darwin15.6.0)
System info:      Darwin blackbox 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64
```

``` 
 brandon at blackbox in ~
$ zcompare:33: defining function based on alias `ls'
zcompare:33: parse error near `()'
zcompare:zcompile:2: can't read file: /Users/brandon/.zim/modules/syntax-highlighting/external/highlighters/main/test-data/function.zsh
```

**Comment by ericbn** [comment]
@bcatubig, did you manually update your `~/.zlogin` file too? The commit only changes the template, but not the actual user dotfile...

**Comment by bcatubig** [comment]
@ericbn -- all good now! Thanks

**Comment by jeffdupont** [comment]
worked for me as well! thanks
