### ISSUE TITLE
theme "eriner" do not work correctly in CentOS 7 Zsh 5.0.2 

### ISSUE THREAD

**Issue by wweir** [Eriner/zim#208]
```zsh
Zim commit ref:   12e4ee2
Zsh version:      zsh 5.0.2 (x86_64-redhat-linux-gnu)
System info:      Linux udp 4.4.0-89-generic #112-Ubuntu SMP Mon Jul 31 19:38:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
Description
-----------
Theme 'eriner' do not work correctly in CentOS 7 default Zsh version.
Some colors do not work

Steps to reproduce
------------------
1. install Zsh in CentOS 7
2. install zim
3. change zim to branch zsh-5.0
3. change theme to "eriner"

Images or other information
---------------------------
![image](https://user-images.githubusercontent.com/2841254/29510749-8005ecfc-868f-11e7-8728-26a63b9f4dbf.png)

**Comment by Eriner** [comment]
This kind of issue is setup specific, and is using a zim-deprecated version of zsh in the legacy branch. I think the solution here is to switch your prompts. If you really, really like the prompt and want to fix it, I'd be happy to merge a fix.
