### ISSUE TITLE
Prompt shows garbage characters

### ISSUE THREAD

**Issue by asarkar** [Eriner/zim#213]
```
Zim commit ref:   2a9a003
Zsh version:      zsh 5.2 (x86_64-apple-darwin16.0)
System info:      Darwin mbp-2016.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```
Description
-----------
Prompt shows garbage characters.
![zim](https://user-images.githubusercontent.com/1302775/30365275-1747ac0c-981c-11e7-8b85-7c228fe8f278.jpg)

Steps to reproduce
------------------
?

Images or other information
---------------------------
Attached.

**Comment by Eriner** [comment]
Install powerline fonts.

**Comment by asarkar** [comment]
@Eriner and then, which font should I choose after installing powerline fonts? Should this not be part of the Zim installation Wiki if you've a dependency on powerline fonts?

**Comment by Eriner** [comment]
You didn't search the current active issues.
See: https://github.com/Eriner/zim/issues/169

**Comment by asarkar** [comment]
I did, but I didn't know about the additional font requirement, so didn't relate it to my problem. You didn't say, which is why that issue exists, and this one too.

**Comment by Eriner** [comment]
Check my newest comment there as well.

**Comment by asarkar** [comment]
Still garbage
```
Copying fonts...
Powerline fonts installed to /Users/asarkar/Library/Fonts
```

```
 ✘ asarkar@mbp-2016  ~/fonts   master  
 ✘ asarkar@mbp-2016  ~/fonts   master  
```

**Comment by asarkar** [comment]
After installing Powerline fonts, one of those need to be set from Terminal -> Preferences -> Font -
 Change. FWIW, I'm using Ubuntu Mono Derivative Powerline 18 pt. with Pro terminal as my default profile.

**Comment by charleslouis** [comment]
Ubuntu Mono Derivative Powerline or Fira Code worked for me
