### ISSUE TITLE
FYI - Step 2. always fails if run in iterm2

### ISSUE THREAD

**Issue by rhysburnie** [Eriner/zim#214]
Hi,

Whenever I use zim and set it up on a new mac, stpe 2 would always fail and I'd spend ages trying to workout how to get it to work.

Today same thing, but then I tried running the command in the default Terminal app and it worked fine.

Thought you might like to know, maybe a note to say to run it in Terminal rather than iterm2 

After that iterm2 was working fine.

No idea why it behaves this way

Cheers

**Comment by rhysburnie** [comment]
wait no... tried again to confirm and pasting in terminal also throws:

`-sh: syntax error near unexpected token `done'`

not sure how i managed to get it to work

**Comment by rhysburnie** [comment]
Now always consistently throws

```
AU-00237:~ burniep$ setopt EXTENDED_GLOB
-sh: setopt: command not found
AU-00237:~ burniep$ for template_file ( ${ZDOTDIR:-${HOME}}/.zim/templates/* ); do
-sh: syntax error near unexpected token `('
AU-00237:~ burniep$   user_file="${ZDOTDIR:-${HOME}}/.${template_file:t}"
AU-00237:~ burniep$   touch ${user_file}
AU-00237:~ burniep$   ( print -rn "$(<${template_file})$(<${user_file})" >! ${user_file} ) 2>/dev/n$
-sh: /dev/n$: Permission denied
AU-00237:~ burniep$ done 
-sh: syntax error near unexpected token `done'
```

as it was originally

**Comment by Eriner** [comment]
You need to run the commands in a zsh shell, as the instructions describe.
```
AU-00237:~ burniep$ setopt EXTENDED_GLOB
-sh: setopt: command not found
```
As the above mentions `sh`, this indicates this is being run under the default shell interpreter as opposed to zsh.
