### ISSUE TITLE
'archive' command issue

### ISSUE THREAD

**Issue by djape** [Eriner/zim#220]
```
Zim commit ref:   5564c87
Zsh version:      zsh 5.4.2 (x86_64-apple-darwin17.0.0)
System info:      Darwin Mac.local 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64

```
Description
-----------
zmodules=(archive...)
'archive' command creates 0 size (corrupted) archive, probably because of undefined _bzip2_bin/_gzip_bin in archive file.

Steps to reproduce
------------------
archive test.tar.bz2 test.txt

**Comment by ericbn** [comment]
@Eriner, why do we have the `${_gzip_bin}` and `${_bzip2_bin}` variables? I don't see any zim code setting them.

Maybe we could just do `--use-compress-program="gzip"` or `--use-compress-program="bzip2"` directly?

**Comment by Eriner** [comment]
This is a leftover from when we supported using `pigz` and `pbzip`, but was removed due to invalid archive issues. I'm okay with cutting this flag entirely.
