### ISSUE TITLE
Broken navigation of multiline command from history

### ISSUE THREAD

**Issue by sodiumjoe** [Eriner/zim#223]
For bug reports, please provide the following information:

In a terminal, run `zmanage info` and paste the output below:

```
zmanage info
Zim commit ref:   7a086f1
Zsh version:      zsh 5.4.2 (x86_64-apple-darwin16.7.0)
System info:      Darwin jmoon 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

- gist of .zimrc: https://github.com/sodiumjoe/dotfiles/blob/master/zimrc
- gist of .zshrc: https://github.com/sodiumjoe/dotfiles/blob/master/zshrc

Description
-----------
I've reproduced this with my own prompt theme as well as with the default `eriner` theme. If you use <C-r> or up arrow to navigate to a previous command that spans multilines and try to edit the command, the cursor appears in the wrong position, and edits happen at a different incorrect position.

Steps to reproduce
------------------
```
$ ls foo \
bar
```

up arrow to return that the previous command
up arrow to go to the first line of the command
cursor appears in a weird position. If you type characters, they appear in a weird position.

**Comment by ericbn** [comment]
What are you considering weird positions? Can you please describe exactly which positions?

What I get (also using `zsh 5.4.2` under MacOS) is not weird to me...

**Comment by sodiumjoe** [comment]
Here's a gif of what's happening:

![2017-11-16 at 2 38 pm](https://user-images.githubusercontent.com/845857/32919798-df90e876-cadb-11e7-96f5-cfaff00fa0e5.gif)

I'm actually not sure why I thought it was related to git-info, but it seems like it's happening even with git-info turned off.

**Comment by Plloi** [comment]
Looks lime you've been mixing the zimframework repo with this one, try backing up your .zim folder and pulling a fresh copy from this repo.

**Comment by sodiumjoe** [comment]
@Plloi i just did a completely fresh install and still seeing the same behavior.

**Comment by ericbn** [comment]
I see a similar issue reported at https://github.com/robbyrussell/oh-my-zsh/issues/4374 and one suggested solution was

> I recently ran into the same problem, what solved it for me was adding `export LANG='en_US.UTF-8'` at the beginning of `.zshrc`.

Actually that's my current `LANG` value too. And I also do

    unset LC_ALL
    unset LC_CTYPE

**Comment by Eriner** [comment]
```
$ cat /etc/locale.conf 
LANG=en_US.UTF-8
```

https://www.freedesktop.org/software/systemd/man/locale.conf.html

**Comment by sodiumjoe** [comment]
Awesome, thanks, that fixed it! Now to figure out where my weird LANG value (`en_US@currency=USD.UTF-8`) came from.
