### ISSUE TITLE
Tab completion with no matches eats line above with steeef theme

### ISSUE THREAD

**Issue by wardls** [Eriner/zim#227]
```
Zim commit ref:   8aa086c
Zsh version:      zsh 5.4.2 (x86_64-apple-darwin17.0.0)
System info:      Darwin space-machine 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64
```

- gist of .zimrc: [https://gist.github.com/wardls/2dee2d4125df5aa9b9e60eb1f393ef4b](https://gist.github.com/wardls/2dee2d4125df5aa9b9e60eb1f393ef4b)
- gist of .zshrc: [https://gist.github.com/wardls/4c682a58ca9e753f6a08f99ea4a47a6f](https://gist.github.com/wardls/4c682a58ca9e753f6a08f99ea4a47a6f)

Description
-----------
Tab completion with no matches eats the line above it when using the steeef theme. See the gif linked below.

Tested with a clean zim installation.

Images or other information
---------------------------
![https://thumbs.gfycat.com/GreenThirdFennecfox-size_restricted.gif](https://thumbs.gfycat.com/GreenThirdFennecfox-size_restricted.gif)

Similar to [https://github.com/sorin-ionescu/prezto/issues/1245](https://github.com/sorin-ionescu/prezto/issues/1245) but I already have an updated zsh.

**Comment by Eriner** [comment]
Hmm... I can't reproduce this issue. Do you experience this in all the terminals you have (iTerm2, Terminal, etc?)

**Comment by wardls** [comment]
I found the problem.

For some reason I had set my default shell to `/bin/zsh` which is zsh version 5.3 installed by mac os. Default shell should have been set to the homebrew installed version at  `/usr/local/bin/zsh`.

This is not permitted by default on mac os which is what probably led to my mistake (you should edit `/etc/shells` to include `/usr/local/bin/zsh`)
