### ISSUE TITLE
history-substring-search not working?

### ISSUE THREAD

**Issue by rclough** [Eriner/zim#23]
I can't tell if this is a bug for the framework, or the module, but it seems I cannot get history-substring-search to work. It's in my `.zimrc`:

```
zmodules=(directory environment git history input utility custom 
          syntax-highlighting history-substring-search spectrum prompt 
          completion)
```

but pressing up/down (or also esc+j/k since I'm in vi mode) seems to do nothing out of the ordinary? I feel like I'm missing something? I have no idea how to debug this.

**Comment by rclough** [comment]
well, turning off vi mode seems to fix it. I'm not sure how to activate it in vi-mode. I'll close cause it's probably my own fault

**Comment by Eriner** [comment]
Using <esc>k/j will not work, as those keys are not currently bound to anything other than the default up/down. Not sure why that would change the normal arrow keys functionality, though. Check how the keys are bound with the init.zsh file of the history-substring-search module.

I plan to bind those eventually by detecting vi/emacs mode, but it's not available at the moment.

**Comment by rclough** [comment]
I haven't really altered much from a pretty straightforwards zsh installation with zimrc, ie I havent added any keybindings myself. I haven't ben using zsh very long so my knowledge of how vi mode works isn't great, I just figured I'd turn it on since I'm a vi user. I know a lot of base vi installations (not talking about zsh) disable the use of the arrow keys, so maybe zsh vi mode is imitating that?

**Comment by Eriner** [comment]
If your `${EDITOR}` variable contains `*vi*` then it will enable vi mode by default. I will have a __real__ fix for this issue next week.

**Comment by rclough** [comment]
FWIW, I have no `$EDITOR` set

**Comment by Eriner** [comment]
You should set it to `vim` or `nvim` then. ;)

**Comment by rclough** [comment]
I would but.....I've lived without it for so long and I'm pretty sure the only thing that I need it for is git, which seems to assume vim anyways.

Hadn't heard of neovim yet though, very interesting!

**Comment by gavsiu** [comment]
I was wondering why my history-substring-search stopped working. I recently set my default editor in `/etc/profile` to vim and when I went back after reading this to comment it out, the history-substring-search started to work after reboot again.
