### ISSUE TITLE
GNU ls and dircolors not detected by ZIM on Darwin

### ISSUE THREAD

**Issue by PatTheMav** [Eriner/zim#230]
With the current zim version (41c2232) the utilities module has been changed, specifically the detection of BSD/Darwin.

Homebrew allows to install Coreutils which contain GNU versions of `ls` and `dircolors`, which were correctly detected by ZIM if symlinked to `/usr/local/bin`. With the new versions these aren’t detected anymore and `ls` stays colourless.

This is not a bug, but a regression in functionality. But would be nice if ZIM could detect a GNU version being available even on BSD systems.

**Comment by Eriner** [comment]
Not exactly related, but I've fixed a bug related to color detection and support in abbeeb9.

**Comment by ericbn** [comment]
@PatTheMav, previous code was not not able to detect GNU coreutils running on a BSD/Darwin OS, but rather was assuming that GNU was present when `dircolors` was present. That is not always true, since you can have GNU without `dircolors` (in [Termux](https://termux.com/) for example).

But you've got a point. What do you suggest?

**Comment by ericbn** [comment]
Also, as briefly discussed in https://github.com/Eriner/zim/pull/225, we're now just calling `dircolors` in GNU if there's a `${HOME}/.dir_colors` file...

**Comment by ericbn** [comment]
> Not exactly related, but I've fixed a bug related to color detection and support in abbeeb9.

@Eriner, I added my comments at the commit and at #125. We can continue the discussion at #125.

**Comment by ericbn** [comment]
For the current issue, what we can do is test the commands with the different parameters.

### ls 
```
if ls --color=auto >/dev/null 2>&1; then
  # GNU

elif ls -G >/dev/null 2>&1; then
  # BSD

  # "-G" might also mean something else in other distributions,
  # so not sure if it's reliable to say "-G" mean "Enable colorized output" here
fi
```

Not sure how a stock OpenBSD would behave to `ls -G`. We currently have

    # stock OpenBSD ls does not support colours at all, but colorls does.
    if (( ${+commands[colorls]} )); then
      alias ls='colorls -G'
    fi

so we would need to adapt the logic above according to this scenario too.

### grep

I think it's worth using the same approach for grep too, as for example [Termux](https://termux.com/) uses a version of BusyBox that does not support `grep --color=auto`.

```
if echo -n 'zim' | grep --color=auto 'zim' >/dev/null 2>&1; then
  # Supports colour

fi
```

And the same care with OpenBSD would have to be taken, as we currently have

    if [[ ${OSTYPE} == openbsd* ]]; then
      if (( ${+commands[ggrep]} )); then
        alias grep='ggrep --color=auto'
      fi
    else
     alias grep='grep --color=auto'
    fi

@Eriner, @PatTheMav, thoughts?

**Comment by PatTheMav** [comment]
@ericbn Sounds good to me - I'm pondering if there's another way that avoids actually calling `ls` to check for features, e.g. checking if `gls` exists, as coreutils are using a prefix by default. Alas that prefix is user-changeable, so the check would fail for those users.

_Maybe_ instead of checking for both features, you could do this (works on my local copy like a charm):

```
  if [[ ${OSTYPE} == (*bsd*|darwin*) ]]; then
    ...
  fi

  if ls --color=auto >/dev/null 2>&1; then
    unset LSCOLORS
    unset GREP_COLOR
    # GNU
    ...
  fi
```

So we set the `ls` options for BSD and only _if_ a coreutils `ls` is available, we set those options (and remove the BSD environment variables to avoid polluting it with useless stuff). Would also keep the amount of conditional branches down.

On another note, what was the reasoning behind removing the ability to use `dircolors`' default settings? I don't feel the need to export the defaults into a separate file on all my machines just to make it exist, if evaluating the default output of `dircolors` achieves the same.

**Comment by ericbn** [comment]
I think testing the commands is a more general (and IMHO more elegant) solution. BUT it makes the shell initialization slower.

I did my suggested changes at https://github.com/ericbn/zim/commit/d860aa4 and tested in my machine:

### original code

```
$ bench "zsh -i -c exit"
benchmarking zsh -i -c exit
time                 269.5 ms   (263.2 ms .. 274.7 ms)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 270.7 ms   (268.6 ms .. 272.5 ms)
std dev              2.194 ms   (835.1 μs .. 2.884 ms)
variance introduced by outliers: 16% (moderately inflated)
```

### changed code

```
$ bench "zsh -i -c exit"
benchmarking zsh -i -c exit
time                 285.7 ms   (279.1 ms .. 295.3 ms)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 280.9 ms   (279.2 ms .. 283.7 ms)
std dev              2.693 ms   (345.6 μs .. 3.443 ms)
variance introduced by outliers: 16% (moderately inflated)
```

@PatTheMav, as for your side comment:

> On another note, what was the reasoning behind removing the ability to use `dircolors`' default settings? I don't feel the need to export the defaults into a separate file on all my machines just to make it exist, if evaluating the default output of `dircolors` achieves the same.

We're using "our" colors instead of the `dircolors`' default ones. See #225. If you want to stick with defaults, I hope zim can now provide better defaults than `dircolors`, so you don't need to worry.

**Comment by PatTheMav** [comment]
@ericbn - got it, that change must’ve flown under the radar for me (I update my shell environment every day and it just calls `zmanage update`to update the environment). Guess I’ll have to update/rerun the setup for ZIM to get the dircolors saved.

As for performance, that was the reason why I was trying to find a way to detect installed coreutils on BSD systems with its `ls` being available at a higher priority. Haven’t found any surefire way yet though..

**Comment by PatTheMav** [comment]
I checked out the dircolors change now - so if I want to use Zim’s colours but also keep the file type colouring, I’d have to merge your settings with the default ones into a custom `dir_colors` file? Fair enough, can package that in my Dotfiles.

As for the `ls` issue, the best way in terms of performance could be a config switch in zimrc, telling ZIM that coreutils are available and used instead of BSDs own versions (so you can assume `ls` and `dircolors` are of the GNU flavour).

**Comment by ericbn** [comment]
Reverted most of the changes. Kept the usage of "our" colors on top of the `dircolors` default ones though.

As a note: Current code only works for `ls` in a GNU with coreutils installed, and only with a `grep` that supports colors (not a Busybox one, for example). I think requiring coreutils in GNU and a complete grep is fair enough.

**Comment by PatTheMav** [comment]
Fair enough - thank you for your efforts! 👍🏻

**Comment by ericbn** [comment]
You can still use the `dircolors` default values by adding

    eval "$(dircolors --sh)"

to your `.zshrc` file, either before of after sourcing zim's `init.zsh` script.

**Comment by Eriner** [comment]
@ericbn to follow up on using the defaults, you can also run:
```
dircolors -p > ~/.dir_colors
```

to dump the defaults into a config. This might be worth noting somewhere, perhaps the readme?

**Comment by PatTheMav** [comment]
As I'm using a base16-based theme for my Terminal.app, I've found a `.dir_colors` file based on those - works like a charm.
