### ISSUE TITLE
Add fasd module

### ISSUE THREAD

**Issue by jalberto** [Eriner/zim#24]
Just a suggestion: https://github.com/clvv/fasd

**Comment by Eriner** [comment]
I've heard about the project, but I haven't really looked much at the code until now. The amount of open issues/PRs with so few commits in the last 3 years isn't encouraging. I may look into stripping it of all the POSIX and Bash-specific code. Seeing as the upstream version isn't updated often, merging any upstream changes should be simple. My *guess* would be that it can be made better, especially seeing as we'd have full control over how the cache/etc is implemented.

With that being said, GitHub's formatting for the code is terrible, and I need to fork and open it with vim. Adding this module will take time. If I don't comment on this issue by next week, please don't hesitate to ping me, @jalberto

**Comment by jalberto** [comment]
Thanks Matt,

My main use for fasd is the j command as implemented by prezto.

If you check the Install page page (
https://github.com/clvv/fasd/wiki/Installing-via-Package-Managers#oh-my-zsh)
there is a oh/my/zsh implementation.

There is alternatives to this command, but so far this implementation works
quite well.

Accepted or not, thanks for your work.

**Comment by Eriner** [comment]
Hm, oh-my-zsh just assumes you have it installed and fails if you don't. I would much rather bundle it with zim for both ease-of-install and because the code itself could be cleaned up for a zsh-only implementation.

**Comment by jalberto** [comment]
you are right :)

**Comment by malaverdiere** [comment]
+1 That utility is a major time saver

**Comment by Eriner** [comment]
I've taken a break from creating the tl;dr module, mainly because to do it well will take more effort than I originally planned (proper caching, fetch-on-request, auto-update, etc). I have made initial work on porting this module and will continue next week. Hopefully I will have a working module in a test branch by the end of next week; I have allocated time in the evenings next week specifically to tackle this module.

**Comment by jalberto** [comment]
That sounds great, if you need help testing it just let me know

**Comment by Eriner** [comment]
@jalberto @malaverdiere I've added `fasd` as a module in the "fasd" branch. Please confirm everything works!

Make sure to add 'fasd' to your `zmodules` array in your `.zimrc` and source the `.zlogin` file to zcompile everything!

**Comment by Eriner** [comment]
@jalberto @malaverdiere have either of you had a chance to test the `fasd` module?

**Comment by malaverdiere** [comment]
@Eriner It worked for me. There were no bugs to report.

**Comment by Eriner** [comment]
Thanks @malaverdiere, I've merged the branch into master.
