### ISSUE TITLE
Enable spell correction for commands

### ISSUE THREAD

**Issue by caedus75** [Eriner/zim#25]
Could you add `setopt correct`, probably to the `utility` module, so zsh can offer a suggestion to a misspelled command instead of failing with 'command not found' error

**Comment by Eriner** [comment]
This is something that I never personally liked. I can add it, but I would create a toggleable option in the `.zimrc` file. Is that acceptable?

**Comment by caedus75** [comment]
A toggleable option is a great idea, actually! No problem with that.

**Comment by Eriner** [comment]
Also made a minor followup commit: https://github.com/Eriner/zim/commit/acc3adffcb1a9f82743cacce0e742100a4e22e45
