### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by dlion** [Eriner/zim#27]
Everytime I open a shell:
```sh
/root/.zim/modules/utility/init.zsh:97: parse error near `]]'
```

**Comment by Eriner** [comment]
please paste the output of `zsh --version` and `which safe-rm`

**Comment by dlion** [comment]
My zim repo is up to date, this error appears from the last update:

```
zsh 5.0.2 (x86_64-slackware-linux-gnu)
```

```
>which safe-rm
safe-rm not found
```

**Comment by Eriner** [comment]
Please try upgrading your zsh to the latest version.

**Comment by dlion** [comment]
My repo is already updated:
```
>git pull
Already up-to-date.
```

**Comment by Eriner** [comment]
No, not your repo, your version of Zsh. That version was released in December of 2012. I have no plans on supporting a version of Zsh that old.

**Comment by dlion** [comment]
Oh, my bad.
Uhm I use Slackware 14.1 stable, before today everything works very well!

**Comment by Eriner** [comment]
It should be fixed now. Took an alternative approach to detecting Suse.

**Comment by dlion** [comment]
Now everything works very well, thanks!

**Comment by Eriner** [comment]
I would still recommend using a current version of Zsh. I was able to fix this 'problem' easily out of luck (that Suse also provides 'rm-dir'). In the future, I don't plan on making work-arounds for OLD versions of Zsh.

**Comment by dlion** [comment]
> I would still recommend using a current version of Zsh. I was able to fix this 'problem' easily out of luck (that Suse also provides 'rm-dir'). In the future, I don't plan on making work-arounds for OLD versions of Zsh.
I understand your point of view, currently I use a stable version of Slackware because I need to use it. (Everything have to works without problems)
Anyway thank you for your great job!
