### ISSUE TITLE
Case Insensitive behavior?

### ISSUE THREAD

**Issue by colemickens** [Eriner/zim#29]
zsh without zim:
```
$ mv Colony* colony/
$
```

with zim:
```
$ mv Colony* colony/
mv: cannot move ‘colony’ to a subdirectory of itself, ‘colony/colony’
$
```

Why is "colony" matching "Colony*" and how can I disable it?

**Comment by Eriner** [comment]
If you have the `completion` module enabled, it is disabled.

https://github.com/Eriner/zim/blob/master/modules/completion/init.zsh#L53

Either enable the completion module, or set that option in your .zshrc.
