### ISSUE TITLE
Bad comparing of zsh version

### ISSUE THREAD

**Issue by ishitatsuyuki** [Eriner/zim#3]
Latest zsh seems to be 5.2, but 5.1.1 also exists
5.1.1 is not a float point number. This won't work:
```
if [[ ${ZSH_VERSION} -ge 5.1 ]]
```
Causing:
```
/home/[USER]/.zim/modules/environment/init.zsh:6: bad floating point constant
```

**Comment by Eriner** [comment]
Ah, you're right. Fix incoming.

**Comment by Eriner** [comment]
Should be fixed now. Thanks for reporting this! Let me know if you have any further issues!

**Comment by Eriner** [comment]
Decided to use a more 'fullproof' method here: https://github.com/Eriner/zim/commit/599add14b99b277f85078311bac89b4f30923f76

This also accounts for the odd bracketed-paste bug with Zsh v5.1.1

**Comment by Eriner** [comment]
@ishitatsuyuki due to a bug in the bracketed paste with Zsh 5.1.1, I recommend you update to 5.2 if possible. Had to disable bracketed-paste and url-quote-magic to workaround the bug with that specific version.

**Comment by Eriner** [comment]
Here is a link to the bug: http://www.zsh.org/mla/workers/2015/msg02680.html
