### ISSUE TITLE
Improper handling of bare git repo

### ISSUE THREAD

**Issue by ishitatsuyuki** [Eriner/zim#36]
Running master @ b959569

If you cd into a bare git repo, the git prompt feature will spam you with this:
`fatal: This operation must be run in a work tree`

Improper handling.

**Comment by Eriner** [comment]
Unfortunately, that isn't a Zim-specific issue. This is an issue in prompt themes using VCS info, which reports that bare repos are repos in the same way that it reports folders with a `.git` folder are git repos. Unless I'm wrong, there is no way to differentiate between the two with ease. This is something that would have to be raised upstream; I will not create work-around code for this.
