### ISSUE TITLE
python virtualenv not displayed with eriner prompt

### ISSUE THREAD

**Issue by MichaelAquilina** [Eriner/zim#40]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:

- Zim commit ref: f19a0268eede65f205ae26286dc5b38420f7ba6c
- gist of .zimrc: https://gist.github.com/MichaelAquilina/5e1b1b884abc9cdc92a7
- Zsh version: zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
- gist of .zshrc: 
- $(uname -mosr): Linux 4.2.0-34-generic x86_64 GNU/Linux

Description
-----------
When using the `eriner` prompt theme, the python virtualenv currently selected is not displayed.

Steps to reproduce
------------------
```
apt-get install virtualenvwrapper
mkvirtualenv defualt
workon default
```
Notice how `(default)` is not displayed anywhere on prompt

Images or other information
---------------------------

**Comment by Eriner** [comment]
Not all prompts display the virtualenv; this isn't a bug in the prompt, it's just a feature that doesn't exist.

**Comment by MichaelAquilina** [comment]
What's the correct location to look if I want to modify it for my own use case then?

**Comment by Eriner** [comment]
If you want to add it, you can look at the code in the `steeef` prompt to see how to do it. If you do add it and the code is clean, PR it upstream (here) and I'll take a look and possibly merge it. Thanks!
