### ISSUE TITLE
[completion] .zcompdump file configuration

### ISSUE THREAD

**Issue by sebastianst** [Eriner/zim#42]
I just switched to zim from omz and I love it!

However, I have a feature request for the completion module:
There should be an option, like `zcomplete_dumpfilemode`, that controls whether to use the single default file `.zcompdump` or use a host-dependent `.zcompdump-${HOST}` file. 
Or better yet, if the variable `zcomplete_dumpfile` is provided in `.zimrc`, then this one should be used in lines 19 and the following zcompile-zcompdump block in [completion/init.zsh](https://github.com/Eriner/zim/blob/master/modules/completion/init.zsh#L19)
Then one can choose for themself how to differentiate `.zcompdump` files. I could then set
```zcomplete_dumpfile="~/.zcompdump-${HOST}" ```

This is the default in OMZ (where the zsh-version is also taken into account, but I don't know how important that is...).

Background: I share the same home directory among different Linux systems and distributions (mainly Arch, but also need to login to Ubuntu systems sometimes) where a single shared `.zcompdump` file causes problems, because I load different modules in my `.zimrc` depending on whether `pacman` is present on the system. Other than that, the shared zim configuration doesn't cause any problems so far.

**Comment by Eriner** [comment]
@sebastianst I've added this feature. Thanks for the input. I'm glad you're liking zim! Let me know if you encounter any issues.

**Comment by ericbn** [comment]
For future reference, the completion module moved to a [separate repository](https://github.com/zimfw/completion) after this issue was closed. Check the [settings section under the completion module documentation](https://github.com/zimfw/completion/blob/master/README.md#settings).
