### ISSUE TITLE
Listing and removing orphan packages does not work as intended

### ISSUE THREAD

**Issue by Brottweiler** [Eriner/zim#43]
- Zim commit ref: https://github.com/Eriner/zim/commit/4ac66646c496225ce8a8714b6a2fcabff32aa851
- gist of .zimrc: https://gist.github.com/6cb081de4374c036e42e9d31069265eb#file-zimrc
- Zsh version: `5.2-1`
- gist of .zshrc: https://gist.github.com/6cb081de4374c036e42e9d31069265eb#file-zshrc
- $(uname -mosr): `Linux 4.4.7-1-ck x86_64 GNU/Linux`

Description
-----------

Running `pacol` lists only some of the orphan packages, and `pacor` finds ~~no packages~~ one package and tries to run the second package as a command, while `pacman -Rns $(pacman -Qtdq)` removes all the orphan packages.

Steps to reproduce
------------------

Run `pacol`, `pacor` and `pacman -Rns $(pacman -Qtdq)` and look at the differences. I have noted it below.

Images or other information
---------------------------

Running `pacol` gives:
```
exiv2 0.25-3
lirc 1:0.9.3.a-2
```

Running `pacor` gives this:
```
checking dependencies...

Packages (1) exiv2-0.25-3

Total Removed Size:  7.07 MiB

:: Do you want to remove these packages? [Y/n] n
zsh: command not found: lirc
```

It tries to run the second package as a command? Wut?

Running `pacman -Rns $(pacman -Qtdq)` as we speak gives this:

```
Packages (5) libftdi-compat-0.20-3  libirman-0.4.6-1  libusb-compat-0.1.5-1  exiv2-0.25-3  lirc-1:0.9.3.a-2
Total Removed Size:  10.59 MiB
:: Do you want to remove these packages? [Y/n] n
```

-----

In the files you can notice `#zpacman_frontend='powerpill'` and `# compdef _pacman powerpill=pacman`. These are commented out because I did not want them to possibly affect the outcome of the above. Even with these options removes/reset to default, the issue happens.

**Comment by Eriner** [comment]
Yeah, this is a bug. The subshell in the alias is being evaluated at runtime. This was probably introduced when the `zpacman_frontend` and `zpacman_frontend_priv` stuff was worked out. Give me a bit and I'll fix it.
