### ISSUE TITLE
Minor issues after manual install if zimrc and zshrc already exist

### ISSUE THREAD

**Issue by Brottweiler** [Eriner/zim#45]
- Zim commit ref: https://github.com/Eriner/zim/commit/4ac66646c496225ce8a8714b6a2fcabff32aa851
- gist of .zimrc: https://gist.github.com/6cb081de4374c036e42e9d31069265eb#file-zimrc
- Zsh version: 5.2-1
- gist of .zshrc: https://gist.github.com/6cb081de4374c036e42e9d31069265eb#file-zshrc
- $(uname -mosr): Linux 4.4.7-1-ck x86_64 GNU/Linux

Description
-----------
If `.zimrc` already exists, and doing a manual installation, the `.zimrc` template will be put at the top in the already existing `.zimrc`, and that way create a file with duplicate lines. I had to delete the default part of the file to restore it to what I had before.

If `.zshrc` already exist, it will put 
```bash
#
# User configuration sourced by interactive shells
#

# Source zim
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi
```
at the top of the file, and then remove any escaping characters. This happens in `.zimrc`, also. 

For example, in `.zimrc` in will delete the `\` character in the line `zmodules=(directory environment git history input utility custom \`.

In `.zshrc`, for me, it messed up these lines:

```bash
# Who doesn't want home and end to work?
bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line

alias steam-wine='WINEDEBUG=-all wine ~/.wine/drive_c/Program\ Files/Steam/Steam.exe >/dev/null 2>&1 &'

# color man pages
man() {
    env LESS_TERMCAP_mb=$'\E[01;31m' \
    LESS_TERMCAP_md=$'\E[01;38;5;74m' \
    LESS_TERMCAP_me=$'\E[0m' \
    LESS_TERMCAP_se=$'\E[0m' \
    LESS_TERMCAP_so=$'\E[38;5;246m' \
    LESS_TERMCAP_ue=$'\E[0m' \
    LESS_TERMCAP_us=$'\E[04;38;5;146m' \
    man "$@"
}
```

Unfortunately I do not have the messed up files since I fixed them and later realised I should report it. In these 3 functions, it removed escaping characters like the `\` and so on.

Steps to reproduce
------------------
1. Have a pre-made `.zimrc` with (custom) defaults and a `.zshrc` with functions that uses escaping characters like the above.
2. Install Zim manually.
3. Compare the old and new `.zimrc` and `.zshrc`.

Images or other information
---------------------------

1. I suppose if `.zimrc` already exist, it should not put things in it, maybe?
2. Make it so it does not remove escaping characters in `.zimrc` or `.zshrc`.
3. If the source zim if part is already in `.zshrc`, my guess is that next install it will get added in there again, so it's there twice. This can be a problem when it comes to dotfiles.

---

And a question regarding manual installation, what is the appropriate way of updating Zim? Is it by just running `git pull --recurse-submodules` (`--recurse-submodules` because submodules)?

**Comment by Eriner** [comment]
I can see why this may happen, but I don't have time to debug this at the moment. A possible fix may involve altering the `print` arguments in the install? The escapes will need to be processed literally.

**Comment by Eriner** [comment]
@Brottweiler can you please test that branch for me to confirm that it fixes the issue? Thanks!

**Comment by Brottweiler** [comment]
What would be the proper way, after a manual install, to "reinstall" this? 

Would it be to switch branch to `issue-45` then run the installer, or do anything else before that?

**Comment by Eriner** [comment]
you'd have to clean out your personal .z* files. Try running [this script](https://github.com/Eriner/zim/blob/management/tools/zim_remove) to remove zim initialization and such. Kill two birds with one stone, test both! (back everything up first, of course).

Then yes, run the 'installer' from the readme, except switch to the issue-45 branch before running that 6-liner. Thanks!

**Comment by Brottweiler** [comment]
Didn't work, here is the messed up lines. Compare to the above.

```
bindkey '[1~' beginning-of-line
bindkey '[4~' end-of-line

alias steam-wine='WINEDEBUG=-all wine ~/.wine/drive_c/Program Files/Steam/Steam.exe >/dev/null 2>&1 &'

    env LESS_TERMCAP_mb=$'[01;31m' 
    LESS_TERMCAP_md=$'[01;38;5;74m' 
    LESS_TERMCAP_me=$'[0m' 
    LESS_TERMCAP_se=$'[0m' 
    LESS_TERMCAP_so=$'[38;5;246m' 
    LESS_TERMCAP_ue=$'[0m' 
    LESS_TERMCAP_us=$'[04;38;5;146m' 
```

Also, it still, maybe unavoidable, duplicates the templates (adds the new template ontop of the existing file inside of it).

**Comment by Eriner** [comment]
> Also, it still, maybe unavoidable, duplicates the templates (adds the new template ontop of the existing file inside of it).

Running the `zim_remove` script in the maintenance branch should remove the template code from your personal dotfiles.

In both of my tests, before I asked you to test and just now, it seems to be working on my end..
![looks fixed](https://i.eriner.me/zim_escape_looks_fixed.png)

**Comment by Brottweiler** [comment]
Ah, yes I didn't run `zim_remove` since I assumed it would remove the file and not the specific template content, so that solves that.

Hmm, that's strange, maybe I did something wrong. I did switch branch before I ran it. Although, I suppose maybe it is fixed and even so it's not like it's an issue right now anyway. Maybe close and reopen if anyone else would report it, I wouldn't run into it again since it's already installed and I wouldn't need to run it on another machine/install since I have dotfiles.

**Comment by Eriner** [comment]
Sounds good. It seems fixed in my testing, but I could also be wrong. I'll close this, and if someone else has this issue we can re-investigate. Adding the `-r` option to `print` causes it to ignore `echo` escape sequences, and therefor doesn't print the colours and whatnot. This, has seemingly fixed the problem. Again, we can re-investigate if someone else has this issue in the future.

Funny enough, working around the escape sequence required that I add two blank lines to the top of all the templates, as I can't add a '\n' in the print anymore. Oh well. Thanks anyway for testing. :)

**Comment by Brottweiler** [comment]
>Funny enough, working around the escape sequence required that I add two blank lines to the top of all the templates, as I can't add a '\n' in the print anymore.
Oh, yeah, I noticed that. I guess that's a minor inconvenience that can be easily manually fixed (which doesn't *need* to be fixed), so that works. Thanks for helping.

**Comment by Eriner** [comment]
No problem. Hopefully this took care of the issue.
