### ISSUE TITLE
wrong ls alias on OpenBSD

### ISSUE THREAD

**Issue by gyakovlev** [Eriner/zim#47]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:

- Zim commit ref: 6cb9d54ffb2039c13db6c15628de569b1d4526e1
- gist of .zimrc: Default one.
- Zsh version: 5.2
- gist of .zshrc: Default one.
- $(uname -mosr): OpenBSD current

Description
-----------

There is no -G option for default OpenBSD version of /bin/ls
To get ls colors one should install colorls utility, this one will have -G option.

So if you want zim to work on OpenBSD you should [[ -x /usr/local/bin/colorls ]] and use this one as alias ls='colorls -G'

Steps to reproduce
------------------
install zim
launch zsh
type ls

Images or other information
---------------------------

**Comment by Eriner** [comment]
Care to submit a PR? I don't have any BSD machines to test on at the moment.

**Comment by gyakovlev** [comment]
Sure, will try to make a PR once I finish setting up new machine.
