### ISSUE TITLE
"cd .." short command

### ISSUE THREAD

**Issue by Brottweiler** [Eriner/zim#49]
This was a feature in [Prezto](https://github.com/sorin-ionescu/prezto), which I was missing now. What it does, is when you type `..` it would alias that to `cd ..`, but also the more you typed `..`, the more it would add onto the command. 

For example, if I wanted to go back two folders, I could type `....` which would automatically change it to `../..` which would run `cd ../..`.

I don't know what in prezto did this, but I did just find the [Directory module](https://github.com/sorin-ionescu/prezto/blob/master/modules/directory/init.zsh) which are setting some options, but I am not sure if that's it, cause I could just set those manually in that case.

**Comment by Eriner** [comment]
Yes, I can add this.

**Comment by Brottweiler** [comment]
A correction: I think when I typed "the more you typed `..`", I meant just one dot. I think when you've already typed `..`, all you have to do is type `.` one more time to get `../..`, and the more you type `.`, the further back you would go.

**Comment by Eriner** [comment]
Yes, that is correct.

**Comment by Eriner** [comment]
In thinking about where this should go, I think I've decided the 'utilities' module to be the best fit. Both the 'environment' and 'directory' modules just set Zsh options. Seeing as this is interactive, I think the 'utility' module is the place for this. I'll start implementing this shortly. This will, of course, be an opt-in feature that defaults to off.

**Comment by Eriner** [comment]
Done! Just do a `git pull` and add `zdouble_dot_expand='true'` to your `.zimrc` to enable!
