### ISSUE TITLE
Problem with prompts

### ISSUE THREAD

**Issue by ishitatsuyuki** [Eriner/zim#5]
Prompts other than "steeef" and "eriner" are not working as they are considered.
For example, I got this when I selected "minimal":
```
$(prompt_user)$(prompt_jobs)$(prompt_vimode)$(prompt_status)                                                                                $(prompt_path)$(prompt_git)
```
I don't know why but after this it works like the screenshot:
```
prompt eriner
prompt minimal
```

**Comment by Eriner** [comment]
Just pushed a fix. This has to do with the use of single vs double quotes (literal vs non-literal). Check if it (minimal) works now.

**Comment by ishitatsuyuki** [comment]
Looks nice.

**Comment by Eriner** [comment]
Great. Thanks for the report. Also fixed this for the gitster prompt.
