### ISSUE TITLE
Updating and uninstalling

### ISSUE THREAD

**Issue by Brottweiler** [Eriner/zim#50]
Maybe add in README or in wiki the proper ways of updating Zim and uninstalling it?

Since Zim uses submodules, I suppose `git pull --recurse-submodules` is the proper way to update it?

**Comment by Eriner** [comment]
It should be added in both places. But what do you think of a `.zim/scripts` or `.zim/tools` with functions that accomplish this, ex: `zim_update`, `zim_reset`, `zim_remove`? Additional things like `zim_clean_cache`, `zim_build_cache`, `zim_debug`, `zim_info`, etc could also be added and optionally enabled.

**Comment by Brottweiler** [comment]
Sounds useful, sure.

**Comment by Eriner** [comment]
Any additional functionality worth exposing?

**Comment by Brottweiler** [comment]
Not what I can think of.

**Comment by Eriner** [comment]
Okay. I've opened https://github.com/Eriner/zim/issues/51, but I'm also keeping this open to note that update/removal functionality should be in the `README.md`.

**Comment by protist** [comment]
I'm not sure if this is a separate issue, but it'd be great to also add information on adding and updating custom submodules. (e.g. [zshmarks](https://github.com/jocelynmallon/zshmarks)). I just cloned it into `~/.zim/modules/`. I'm not sure if that is correct, but `zim` seems to source it fine.

**Comment by Eriner** [comment]
@protist that is the correct way to handle it! I've started to do some work in the management branch regarding user framework-management tools.

**Comment by aplatest** [comment]
The out-of-the-box experience of zim could be better:
- An install script, I really don't like the way it is done now (just having exactly the same lines in a script would be enough)
- An update script, oh-my-zsh does this quite well
- An uninstall script, nobody seems to be interested in this (I mean oh-my, prezto etc)
- And then maybe a firstboot-hook to give the user some info where to look next, what to change

**Comment by Eriner** [comment]
@aplatest: see: https://github.com/Eriner/zim/issues/51

**Comment by Eriner** [comment]
I've now added notes to the main README.md about updating and removing zim. Additionally, this requires the `meta` module be enabled, which is now a default module in `templates/zimrc`.

**Comment by jitendravyas** [comment]
I'm using ZIM bit not able to update it

`command not found: zmanage`

**Comment by Brottweiler** [comment]
@jitendravyas are you using an old commit, or have you not enabled the zmanage module?

**Comment by jitendravyas** [comment]
What do you mean by old commit? I guess I installed ZIM 5-6 months ago. What do I need to do now to have latest version?

**Comment by Brottweiler** [comment]
Have you updated Zim since then? Try running the command that's inside the [zim_update](https://github.com/Eriner/zim/blob/master/tools/zim_update) script, inside your zim installation folder.

**Comment by jitendravyas** [comment]
ok ran all these commands and updated https://github.com/Eriner/zim/blob/master/tools/zim_update

How to enable meta module?

**Comment by Brottweiler** [comment]
You could compare your `.zimrc` file with the [default](https://github.com/Eriner/zim/blob/master/templates/zimrc) one, and edit it accordingly. Notice that in the `zmodules=()` there is `meta` included, which is probably not included in your file.

**Comment by jitendravyas** [comment]
81 vs 241 lines of code.

**Comment by Brottweiler** [comment]
What are you asking? Look at the `zmodules` line.

**Comment by jitendravyas** [comment]
Replaced default file with my existing file. Restarted terminal. `zmanage` command is working now.

**Comment by jitendravyas** [comment]
I didn't get how to install modules? I think I lost my modules settings with previous replacing. https://github.com/Eriner/zim/blob/master/modules/completion/README.md

**Comment by Brottweiler** [comment]
You edit the `zmodules` line. The default one is:

```sh
zmodules=(directory environment git history input utility meta custom \
          syntax-highlighting history-substring-search prompt completion)
```

Mine is this:

```sh
zmodules=(directory environment git history input utility meta custom \
          syntax-highlighting history-substring-search prompt completion spectrum archive ssh pacman)
```

Notice how I've just added `spectrum archive ssh pacman` after the default ones.

**Comment by jitendravyas** [comment]
Does it mean that Bold ones on this page are already installed https://github.com/Eriner/zim/wiki/Modules

Are these pre-installed/activated module?
```
zmodules=(directory environment git history input utility meta custom \
          syntax-highlighting history-substring-search prompt completion)
```

**Comment by Brottweiler** [comment]
It sais the **bold** ones are highly recommended modules.

Yes, all those are the activates modules, but not all available modules are activated.
