### ISSUE TITLE
Auto-set window title

### ISSUE THREAD

**Issue by protist** [Eriner/zim#52]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:
- Zim commit ref: 6dce750
- gist of .zimrc: I can provide if necessary.
- Zsh version: 5.2
- gist of .zshrc: I can provide if necessary (currently it's pretty busy)
- $(uname -mosr): Linux 4.5.1-1-ARCH x86_64 GNU/Linux
## Description

Window titles are not automatically set.
## Steps to reproduce

Open a new window/tab (e.g. in terminator).
## Images or other information

Prezto has the ability to [automatically name windows](https://github.com/sorin-ionescu/prezto/tree/master/modules/terminal#auto-title) with the current command or directory. Is this possible with zim?

**Comment by protist** [comment]
I put the following code at the end of `~/.zshrc`
```
case $TERM in
    xterm*)
        precmd () {print -Pn "\e]0;${PWD/#${HOME}/~}\a"}
        ;;
esac
```
which works perfectly. This code abbreviates the home directory to `~`, but you can remove the `/#${HOME}/~` part if you don't like that.

**Comment by gavsiu** [comment]
This is what I'm using:

    case $TERM in
      xterm*|*rxvt*)
        temu="urxvt"
        preexec () {
          if [[ $(echo -e $1 | tr -d '\040\011\012\015') = "reset" ]]; then
            1="$temu"
          else
            1="$1 - $temu"
          fi
          print -Pn "\e]0;$1\a"
        }
      ;;
    esac

It shows the last command run unless it was `reset`. I tried to emulate how apps like Firefox and Atom had their name in the title.

**Comment by protist** [comment]
@gavsiu Looks good. For me, the window title is important because I often have many tabs open in my terminal emulator (`terminator`). I rely on titles on each tab to tell them apart. However, since the tab width depends on the amount of text in it, I prefer having a minimum amount of information in them, and thus the working directory is enough for me.

**Comment by Eriner** [comment]
So, I'd like to get a feel of what you believe the ideal naming structure to be. Your example, @gavsiu, appends 'urxvt' even if you aren't using urxvt. This seems silly. My ideal window title for a terminal is:

`Terminal - user@host:${PWD}`

Concise, and allows me to quickly identify what is what. Any thoughts on alternatives? It would be rather simple to allow for "custom" titles. Given a set of keywords, construct a string that defines the title. Ex:

`title="${USER}@$(hostname --short):${PWD}"`

**Comment by protist** [comment]
I just thought I'd show a screenshot indicating how the titles are useful in `terminator`. And how terseness is important.
![Terminator tabs](https://cloud.githubusercontent.com/assets/646668/15270714/4cd3b93a-1a6c-11e6-88f7-4dd8c71fe619.png)

However, if it's all customisable, then it shouldn't matter too much.
* * *
Also, I've found a use case where my code fails.

1. Create a new tab (window title is set correctly).
2. `cd` somewhere (window title is set correctly).
3. Create a split window and `cd` somewhere in this new split window (window title is set correctly).
4. Select either window at will (window title changes correctly).
5. Close the new split window (window title should revert to the remaining window, but **fails**).
6. `cd` in the remaining window (window title is now fixed, and **fails** to update).

**Comment by Eriner** [comment]
@protist I think making the string customizable is the best bet. Thanks for the feedback!

**Comment by protist** [comment]
Thank *you* for the excellent work on zim… it's great having a zsh framework with an extremely responsive developer!

**Comment by Eriner** [comment]
Well, to be fair, I haven't been doing a great job as of late in terms of resolving the many issues that have been discovered.. That said, now that I'm a bit more settled in my new job and location, I should be able to take care of things more quickly now and in the future!

**Comment by protist** [comment]
Thanks for your honesty… However, you are _still_ the most responsive dev by far! I look forward to the future improvements!

**Comment by aplatest** [comment]
Do we want this in a plugin? It is a must-have for most people, but I would like to turn it of for myself. Tiling WMs often hide window-titles.

**Comment by gavsiu** [comment]
Yes, there should be an option to disable. Although we may be using tiling wms, not everyone uses them. Also, I have window titles displayed in my lemonbar and it shows in rofi window switcher.

**Comment by aplatest** [comment]
Then do it as a plugin, or add it to utility/init.zsh? I can add something simple and then we can improve it from there. 
We can start with: `user@host:path` and maybe something with the return value of the last command would be good (basically on more very simple prompt).

**Comment by Eriner** [comment]
Not setting/uncommenting the variable in the `.zimrc` file will result in the current behavior (no change).

**Comment by Eriner** [comment]
@protist @aplatest Please check the "termtitle" branch I just pushed (see the commit referenced above) to test this functionality. There are likely some issues with multiplexers like tmux, as well as with terminal emulators that believe it's their job to manage the shell environment (see urxvt, terminator). If we can knock out these issues before I push this to the master, that would be ideal.

**Comment by protist** [comment]
Works very nicely! Thank you for the fix! I like the usage and flexibility of the prompt sequences. However, I do have a couple of issues.

As [above](https://github.com/Eriner/zim/issues/52#issuecomment-219252069), there is a simple use case where this new commit fails too. I've reduced it to a minimal failing example, in terminator.

1. Create a new tab (window title is set correctly).
2. Create a split window (terminator opens new window is same directory, so window title is still correct).
3. Close the new split window.
4. `cd` in the remaining window (window title will no longer change, and fails to update).

This problem was also seen in my hacky [solution](https://github.com/Eriner/zim/issues/52#issuecomment-218064403). However, there is another problem that is unique to the zim commit.

If I run, say, `vim`, the terminal title changes appropriately. When I quit `vim`, the zim-defined title is back, as expected. If I run `mutt`, the title changes appropriately. However, when I quit, the zim-defined title is *not* restored. The title is stuck on the mutt-defined title. I can then `cd` and the title is okay again, but I never see this temporary "stickiness" in my hacky fix. FWIW I have the following in my `muttrc`.

    set ts_enabled = yes
    set ts_status_format = "Mutt%?b?*?"

**Comment by Eriner** [comment]
Meh, it being "sticky" on occasion until the next `cd` seems like a pretty minor bug for what (I believe) is a pretty small code edition. IMO, as long as the title updates **most** of the time, and is corrected upon `cd`, this bug isn't a huge issue. If there's an easy fix that doesn't add a bunch of additional conditionals or anything like that, let me know.

**Comment by protist** [comment]
Yes, I agree that the second part isn't that terrible at all. However, I tried modifying `modules/environment/init.zsh`, replacing the first `chpwd` with `precmd`, and deleting the second. This seems to fix the second problem fine. TBH I have no idea what the difference is and/or any effects on performance; I originally came across the command from a search engine.

In any case, I do find the first part to be more annoying, and something that occurs quite frequently. I'm not sure what the fix is for that part.

**Comment by Eriner** [comment]
`chpwd` is only run when the directory is changed, as opposed to before the prompt is drawn. `precmd` is a bit more aggressive, but if it's necessary in this case, so be it. I can update the branch at some point this weekend.

Regarding the "first bug" you keep mentioning, can you provide that step-by-step with images? Please excuse my ignorance -- I use a tiling window manager and have a hard time understanding the issue you're describing.

**Comment by protist** [comment]
Thanks for the update. Here is a series of screenshots showing the problem. Let me know if it's unclear.

1) Create a new tab (window title is set correctly). It's `~` in this case. You can see from my prompt that I'm in `~`, and the tab title at the bottom shows the same thing.

![screenshot_at_20160930_22 02 21](https://cloud.githubusercontent.com/assets/646668/18991102/c6873432-8759-11e6-9f4c-b4327dd34af5.png)

2) Create a split window (terminator opens new window is same directory, so window title is still correct). Here the new window is beneath the original.

![screenshot_at_20160930_22 02 38](https://cloud.githubusercontent.com/assets/646668/18991107/cea552fc-8759-11e6-8612-d51021f29311.png)

3) Close the new split window. I've closed the lower window, leaving the upper window remaining open.

![screenshot_at_20160930_22 02 48](https://cloud.githubusercontent.com/assets/646668/18991113/d483e0da-8759-11e6-8896-9cc29b6c0433.png)

4) `cd` in the remaining window (window title will no longer change, and fails to update). You can see I'm now in `/home`, whereas the tab title still says `~`.

![screenshot_at_20160930_22 03 01](https://cloud.githubusercontent.com/assets/646668/18991123/e00efc50-8759-11e6-8e76-192edfb7ae04.png)

**Comment by PatTheMav** [comment]
oh-my-zsh has a quite comprehensive module that sets tab and window titles separately, supports the default macOS prompt precmd to set the directory's icon and detects different terminals.

I've been running it as an extra module (I have several that I load _after_ zim in my `.zimrc`) without issue for months now.

**Comment by protist** [comment]
@PatTheMav I presume it's [this module](https://github.com/robbyrussell/oh-my-zsh/blob/3705d47bb3f3229234cba992320eadc97a221caf/lib/termsupport.zsh) that you are referring to? FWIW this also seems to fail when I repeat my steps [above](https://github.com/Eriner/zim/issues/52#issuecomment-250728623). Possibly this is bug in terminator, but I wouldn't know how to check.

**Comment by PatTheMav** [comment]
@protist - yep that's the one. I just checked and noticed, that I added the following to my working copy at line 22:

```
      if [[ "$TERM_PROGRAM" != "Apple_Terminal" ]]; then
        print -Pn "\e]1;$1:q\a" # set tab name
      fi
```

That's probably also the part that appears to break in the issue you described.

**Comment by protist** [comment]
@PatTheMav I'm using Linux, so I'm not sure that this is relevant in my case? It looks like the `print…` line would run all the time for me anyway.

**Comment by Eriner** [comment]
@protist using `precmd` in place of `chpwd` fixes the issue for you correct? If so, I'll just swap them so that we can fix the issue for you and other termite users. I don't think there will be a huge performance hit, it will just cause the title to re-draw more frequently, which I don't think is a huge issue/speed degradation from my limited and quick testing.

**Comment by protist** [comment]
@Eriner Yes, I no longer get the "sticky" title when quitting mutt, if I use `precmd` instead of `chpwd`. (And I can also remove the second `chpwd`.)

Also, I recently moved to terminator-gtk3, which uses vte3. With `precmd`, I no longer see the un-split window problem from [above](https://github.com/Eriner/zim/issues/52#issuecomment-250728623) (I didn't test `chpwd`).

**Comment by Eriner** [comment]
I apologize for the long wait, I've merged this into origin/master! :)
