### ISSUE TITLE
After ZIM: git:1: job table full or recursion limit exceeded

### ISSUE THREAD

**Issue by elmerehbi** [Eriner/zim#57]
After installing ZIM with Oh-my-zsh already installed I started getting the following at every new ZSH terminal:

`git:1: job table full or recursion limit exceeded`

I just noticed that having Oh-my-zsh causes conflicts. How can I uninstall ZIM?

**Comment by Eriner** [comment]
remove the ~/.zim folder, remove the "source zim" lines from you .zshrc.

Though, your problem likely isn't zim itself, but a conflict with oh-my-zsh. You might try removing that first and seeing if that fixes the issue. This type of conflict is mentioned in the Readme.md under the Installation header.

> Installing Zim is easy. **If you have a different shell framework installed (like oh-my-zsh or prezto), uninstall those first to prevent conflicts.** Arch users can install zsh-zim-git from the AUR. It can be installed manually by following the instructions below:

**Comment by elmerehbi** [comment]
After a second though, how can I keep ZIM. Should I uninstall Oh-my-zsh?

**Comment by Eriner** [comment]
To prevent the type of conflicts you're experiencing, you should only have either Zim or oh-my-zsh or prezto installed at any given point.

To remove oh-my-zsh, see here: https://github.com/robbyrussell/oh-my-zsh#uninstalling-oh-my-zsh

Alternatively, this script (on the "in-progress" management feature branch) *should* remove Zim: https://github.com/Eriner/zim/blob/management/tools/zim_remove (Note, this is experimental and marked as an "in-progress" feature). 

Let me know if you run into any additional issues no matter what you choose. I'll do my best to help if I can.

**Comment by elmerehbi** [comment]
Done. Great thank for you help. Now on ZIM :)

**Comment by Eriner** [comment]
Glad you got everything working, and glad I could help!
