### ISSUE TITLE
Git alias conflict with other commands

### ISSUE THREAD

**Issue by Brottweiler** [Eriner/zim#59]
[GraphicsMagick](http://www.graphicsmagick.org/)'s command is `gm`, which is a [git alias](https://github.com/Eriner/zim/blob/master/modules/git/init.zsh#L107) aswell. It is not possible to run GraphicsMagic command without running `git merge` alias.

**Comment by Eriner** [comment]
Actually, you can run `command gm` or `\gm` to ignore the alias.

**Comment by Brottweiler** [comment]
I thought there was a way to ignore the alias, thanks, I will try to remember that!

**Comment by Eriner** [comment]
`command` syntax is best for scripts. I use `\binary_here` frequently if I want specific command flags that would otherwise be overridden by my aliases.
