### ISSUE TITLE
URL quoting doesn't work anymore

### ISSUE THREAD

**Issue by lnicola** [Eriner/zim#60]
- Zim commit ref: 345233741e441ab00c2ce5540aa00a3646d43abc
- gist of .zimrc: https://gist.github.com/lnicola/50140a843e91eb765e64d882d0093279
- Zsh version: 5.2
- gist of .zshrc: https://gist.github.com/lnicola/50140a843e91eb765e64d882d0093279
- $(uname -mosr): Linux 4.6.2-1-ARCH x86_64 GNU/Linux

Description
-----------
URLs are not quoted anymore when pasting them.

Steps to reproduce
------------------
1. Copy an URL
2. Paste it into a terminal

Images or other information
---------------------------
Screenshot: https://i.imgur.com/Fd685XX.png
`$TERM` is `xterm-256color`
Last working commit is 609d94e949a4f091cd3b62dd28264c73b491beb2.

**Comment by Tmplt** [comment]
I'm on the same commit, and experience this issue, but I never knew this was an expected feature; URL quotes were not added in earlier commits (can't recall which, unfortunately). 

```sh
echo $TERM
screen-256color
```

`.zimrc` and `.zshrc` gist: https://gist.github.com/Tmplt/262d6f2e5a49830f66d768eb25be7bc9

**Comment by lnicola** [comment]
Strange, they always were for me. Do you have an older zsh?

**Comment by Tmplt** [comment]
I do not think so:

```sh
zsh --version
zsh 5.2 (x86_64-unknown-linux-gnu)
```

**Comment by Eriner** [comment]
This changed in a recent commit I made. It seems that I boned it. I'll fix this later today.

Suspect commit: https://github.com/Eriner/zim/commit/345233741e441ab00c2ce5540aa00a3646d43abc

**Comment by lnicola** [comment]
@Eriner yes, 3452337 broke it. Sorry if that wasn't clear from my report.

**Comment by Eriner** [comment]
The immediate bug I see is that the `zle` is incorrect. It should be:

`zle -N bracketed-paste bracketed-paste-url-magic`

Though, this does not seem to fix the issue. I don't have time to investigate this now, but the code for the braceted-paste-url-magic function is here: https://github.com/zsh-users/zsh/blob/master/Functions/Zle/bracketed-paste-url-magic

**Comment by lnicola** [comment]
Heh, I missed that. Your fix works for me, but make sure you're pasting an URL that includes the schema.
