### ISSUE TITLE
theme installation?

### ISSUE THREAD

**Issue by PwnArt1st** [Eriner/zim#63]
downloaded numerous .zsh-theme files into both .vim/modules/prompt/themes and /usr/lib/zim/modules/prompt/themes and they do not show up when running prompt -l, i couldnt find any other documentation of what to do, and i have already tried restarting yes.

**Comment by Eriner** [comment]
Sounds like you're using the zim-zsh-git package from the AUR. I am not officially supporting this install method. Please try removing that package and installing via the normal methods. See: https://github.com/Eriner/zim/issues/44
