### ISSUE TITLE
steeef theme will not update git status

### ISSUE THREAD

**Issue by nshtg** [Eriner/zim#66]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:

- Zim commit ref: 5f7a75a969cbfffc6f7e49cffe4be38dc29b9206
- gist of .zimrc: https://gist.github.com/anonymous/d2bc5f9d54ea1c87b527bc7e4443581d
- Zsh version: `zsh 5.1.1 (x86_64-unknown-cygwin)`
- gist of .zshrc: https://gist.github.com/anonymous/c0daff5ad8697298d42876fd9c2c83d1
- $(uname -mosr): `CYGWIN_NT-10.0 2.5.2(0.297/5/3) x86_64 Cygwin`

Description
-----------
The `steeef` theme will not update the git status. You have `cd` out and back in again to update the status. I tested `pure` and `gitster` themes and they both worked as expected. (See screenshot attached)

Steps to reproduce
------------------
Select `steeef`, go into a git repo, change something, profit?

Images or other information
---------------------------
![mintty_2016-07-26_15-41-45](https://cloud.githubusercontent.com/assets/5219415/17140263/259dab5e-5348-11e6-8739-8ee62d0157c6.png)

This problem exists on my MacBook too, running iTerm and a very recent version of zsh, so it is not a windows/cygwin specific problem.

**Comment by Tmplt** [comment]
I can reproduce this issue. Same commit.
* `.zimrc` gist: https://gist.github.com/Tmplt/6eeb78c1eb52c30967a1220982c55d0e
* zsh version: `zsh 5.2 (x86_64-unknown-linux-gnu)`
* zshrc: https://github.com/Tmplt/dotfiles/tree/desktop/zsh/.zsh (all files here are sourced)
* `uname -mosr`: `Linux 4.6.4-1-zen x86_64 GNU/Linux`

**Comment by Eriner** [comment]
see my comment in your PR. The end goal is for it to update automatically as the other prompts do. As of now, I believe it only updates on a `cd` or a call to `git`.
