### ISSUE TITLE
Error with eriner prompt

### ISSUE THREAD

**Issue by xolan** [Eriner/zim#7]
Hi! The `eriner` prompt theme was working just fine until I updated `zim` via `git pull` just now.
Now there seems to be an issue with the arrow font or something.

I'm on ref fbb7482

![zim_1](https://cloud.githubusercontent.com/assets/670050/12037237/577727c2-ae4d-11e5-95bc-db32aae5a2ec.png)

**Comment by Eriner** [comment]
@xolan that means you don't have a powerline-patched font. The only change (to that variable) was https://github.com/Eriner/zim/commit/a08039ca4ad58399514b058612d3b62e0bb2ad63

That is what it *should* look like if you don't have a powerline-patched font.

**Comment by Eriner** [comment]
@xolan this will likely fix your problem: https://simplyian.com/2014/03/28/using-powerline-symbols-with-your-current-font/

**Comment by xolan** [comment]
@Eriner Yes this was indeed due to a system package update, not the prompt theme. Sorry for the inconvenience :)

Was using `zgen` eariler. Loving the simplicity and speed of `zim`though!

**Comment by Eriner** [comment]
@xolan no problem, glad you figured it out. Thanks for bringing this to my attention, though. I had meant to link that blog post in the theme code. Cheers!
