### ISSUE TITLE
[prompt] magicmace: tab-completion screws up prompt some times

### ISSUE THREAD

**Issue by Tmplt** [Eriner/zim#70]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:

- Zim commit ref: 8ac887e8e99a7d6d865fe433291729a3f879eaf2
- gist of .zimrc: https://gist.github.com/Tmplt/62fa02066dc28e6601cdd725c7624f2a
- Zsh version: `zsh 5.2 (x86_64-unknown-linux-gnu)`
- gist of .zshrc: https://github.com/Tmplt/dotfiles/blob/desktop/zsh/.zshrc
- $(uname -mosr): `Linux 4.6.4-1-zen x86_64 GNU/Linux`

Description
-----------
Some times, when using tab-complete for command arguments of flags, the prompt's layout is screwed up, as the image shows:
![broken prompt](https://bad.dragons.rocks/eVnB)
When removing characters, the new left-most location for the cursor is the incorrect:
![very broken](https://bad.dragons.rocks/dVJG)
Because it should be:
![working](https://bad.dragons.rocks/YI7c)

This can also be caused by writing long commands.

Steps to reproduce
------------------
1. Use the `magicmace` theme
2. Utilize tab-completion where it can be used or write a lengthy command.

Images or other information
---------------------------
* Does not occur every time.
* Clearing the command line with ^L works as intended; the cursor is placed in the correct position.

**Comment by Tmplt** [comment]
doing `prompt eriner` and then `prompt magicmace` seems to solve this issue. I'll diff the two themes and see if I can find a difference in options or something.

**Comment by Eriner** [comment]
This likely has to do with the definition of a line-draw hook somewhere.

**Comment by Tmplt** [comment]
I've never heard the term "line-draw hook". When are these used?

**Comment by Eriner** [comment]
To clarify, I was referring to a possibly missing precmd, but that doesn't seem to be the issue.
