### ISSUE TITLE
Couldn't read file .zim/modules/prompt/functions/prompt_lean_setup containing theme lean.

### ISSUE THREAD

**Issue by Brottweiler** [Eriner/zim#73]
- Zim commit ref: https://github.com/Eriner/zim/commit/fc45c8e328ade4fd6aacd0aaaed08732ff2393cb
- gist of .zimrc: https://gist.github.com/anonymous/89588411fdf359df682c5ea15ab96643#file-zimrc
- Zsh version: `5.2`
- gist of .zshrc: https://gist.github.com/anonymous/89588411fdf359df682c5ea15ab96643#file-zshrc
- $(uname -mosr): `Linux 4.7.2-1-ck x86_64 GNU/Linux`

Description
-----------
I just ran `git pull` to update zim, and now I am getting the error `Couldn't read file /home/brott/.zim/modules/prompt/functions/prompt_lean_setup containing theme lean.` when opening terminals and tmux sessions.

Steps to reproduce
------------------
1. Run `git pull`
2. Open a new terminal.

Images or other information
---------------------------
The link is broken; `prompt_lean_setup -> ../external-themes/lean/prompt_lean_setup`. The `external-themes/lean/` directory is empty, but it's not empty in this repository. 

It is an external repository, but I don't have it. I assume I somehow need to "clone" that repo, but I already cloned zim repo, and I'm not sure how to add this other repo?

**Comment by Eriner** [comment]
You likely need to update/init the submodules.

```
$ cd ~/.zim && git submodule update --init --recursive
```

**Comment by Brottweiler** [comment]
That's the command I was looking for, thank you!

For the future... how do I update zim with the submodules?

**Comment by Eriner** [comment]
This is what I eventually plan to merge after I clean some things up and finish the scripts:

https://github.com/Eriner/zim/blob/management/tools/zim_update
