### ISSUE TITLE
meta module - command not found: zmanage

### ISSUE THREAD

**Issue by FuzzOli87** [Eriner/zim#74]
Hello,

I updated zim by pretty much doing everything the ```zmanage update``` command does on the local repo I create when I install it. I added meta to the module list but it does not show up as a valid command when I restart my terminal.

I'm on ArchLinux with everything updated. However, I installed this manually.

Here is the gist of my .zimrc
https://gist.github.com/FuzzOli87/c1c87dbbf2475ab83ce7193fa62645af

**Comment by Eriner** [comment]
I don't understand the question based on your description and the title. What is "zmanage link"? What is the latest commit in your .zim repository?

**Comment by FuzzOli87** [comment]
@Eriner Sorry I wasn't very clear. I meant the command does not exist when I try to use it. I get a "command not found" error when I try to run ```zmanage update```

**Comment by Plloi** [comment]
Your linked zimrc "Duplicates" at line 83 overwriting some(all) previous declarations. particularly zmodules (without meta) on line 94

**Comment by Eriner** [comment]
See @Plloi's comment.

**Comment by FuzzOli87** [comment]
Well that's embarrassing. Thanks!
