### ISSUE TITLE
zmanage info error on macOS

### ISSUE THREAD

**Issue by tasmo** [Eriner/zim#75]
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:

- Zim commit ref: 071ddaf
- Zsh version: zsh 5.2 (x86_64-apple-darwin15.2.0)
- $(uname -msr): Darwin 15.6.0 x86_64

Description
-----------

On macOS the `uname` command does not accept the option `-o`; which is called from  `~/.zim/tools/zim_info`.

~~~ shell
$ zmanage info
Zim commit ref:   071ddaf
Zsh version:      zsh 5.2 (x86_64-apple-darwin15.2.0)
uname: illegal option -- o
usage: uname [-amnprsv]
System info:
~~~

Steps to reproduce
------------------

~~~ shell
$ uname -msr
Darwin 15.6.0 x86_64
~~~

**Comment by tasmo** [comment]
Seem ZIM is not tested on latest macOS versions (not beta). the `ls` command does not understand options beginning with `--` as well.

**Comment by Eriner** [comment]
Yes, I primarily use Linux and not BSD machines, so there may be some differences in command arguments that may cause things to unexpectedly break. It seems that the `uname` command on Darwin systems use a different command syntax. I will remediate this issue shortly. Thanks for the report and sorry it's taken me so long to reply and fix such a trivial issue. :+1: :)
