### ISSUE TITLE
Allow "opting out" of alias definitions in modules

### ISSUE THREAD

**Issue by ZeroKnight** [Eriner/zim#77]
A small feature request as most modules define aliases alongside the functionality that they provide. There are some cases where I would prefer not having the aliases provided by the module, as I either have my own set (like `ls`, I have my own set of about 15 aliases regarding `ls`), or simply don't plan to use them and would rather not have them defined.

I was thinking something along the lines of a counterpart of the `$zmodules` array that specifies what modules should not define aliases. You could do the following:

```
zmodules=(directory environment git ...)
znoalias=(directory)
```

And each module would just check for its existence in `$znoalias` before defining any aliases.

The only thing it wouldn't cover is being able to ditch some definitions, and keep others :sweat_smile: Though you could always just put them in custom at that point, I suppose.

**Comment by Eriner** [comment]
This would require evaluating all of those at runtime of the init scripts. Conditionals around setting aliases  is not something I am going to add, as this would drastically increase complexity and reduce speed. 

I suggest doing one of the following things:
* `unset ls`
* `\ls` <-- temporary ignore
* do whatever you want in your .zshrc after the source of the zim init script.

**Comment by ZeroKnight** [comment]
Reasonable enough, didn't think about the speed impact.
