### ISSUE TITLE
coming from sorin theme (prezto) missing some git details

### ISSUE THREAD

**Issue by stefanosc** [Eriner/zim#82]
Hello and thank you for your work.
I played with it and looks great.

I was wondering if you intend to add anything similar to the git details that sorin prompt provided (action,added,ahead,behind,branch,commit,deleted,modified,position,renamed,stashed,unmerged,untracked) they were very handy...
I have not seen any prompt theme with the same level of detail.

Thank you!

**Comment by ericbn** [comment]
@stefanosc, you mean the `git-info` function in the `git` prezto module, right?

**Comment by stefanosc** [comment]
@ericbn thank you for the quick reply, I mean all the symbols on the right prompt giving you a super handy and quick idea of a git repo. From the git module: https://github.com/sorin-ionescu/prezto/tree/master/modules/git#theming

and yes it is `git-info` function that seems to do the heavylifting for themes.
What do you see? Thanks

**Comment by stefanosc** [comment]
@ericbn actually I could have simply done this earlier:
https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_sorin_setup#L115-L131

**Comment by ericbn** [comment]
Got it. Yeah, zim has its own (simpler) `git` module, that does not have "theming" capabilities as the zprezto one.

I miss this too. I would vote +1 to have this in zim. On the other hand, the zim version might not be backwards compatible with the zprezto one, as it would sound strange for it to keep the same `zstyle ':prezto:module:git:...'` parameter names...

**Comment by stefanosc** [comment]
It would just be great to have  the ability to add these to prompt themes, no need to keep it backwards compatible. I think this feature and the sorin git async are what's missing to any theme I've seen so far..  If I was a bit more experienced with shell and had more time I would like to give it a shot.

**Comment by Eriner** [comment]
The "pure" theme provides async. 

I'd like to keep things as simple as possible, and I don't really see a need for adding all of those git symbol options. If there is something that you would like to change, I think the solution is to take a theme and make your own fork. That seems to be the simplest solution, as I'm betting the majority of users have never changed those options. Thus, the users who can/do change it probably have enough technical prowess to take a theme they like and modify those options slightly.

Adding this functionality seems like a fair amount of work and a code volume increase for functionality used by fairly few individuals. Just my two cents.

**Comment by ericbn** [comment]
Prezto's `git-info` is an improved (and git-specific, of course) version of zsh's `vcs-info`. It's a great building block for constructing prompts.

I was suggesting a version of agnoster prompt for prezto that would use `git-info` at https://github.com/sorin-ionescu/prezto/pull/1168. (Actually that was the prompt I was using, and the only thing I still miss from my prezto setup)

But I love the ideia of keeping zim simple, and would give higher priority to just making it better and even simpler!  :- )

**Comment by Eriner** [comment]
Hmm. I think the _real_ solution here would be to unify **all** of the prompts to use a single set of universal functions, as that would significantly reduce the code duplication between themes. However, this brings additional complexity in the transition and requires forking them from their upstream sources, which I am not against, I just don't have the time to put in that work at the moment.

However, at the present time, unless this is the route we want to go, I'm not sure if this worthwhile (if it's even worthwhile at all).

**Comment by stefanosc** [comment]
Thank you @Eriner for considering this feature.
I will see if I can help putting something together in the coming weeks / months, meanwhile let's see if anyone else thinks this could be useful.

**Comment by Eriner** [comment]
@stefanosc: @ericbn has made a PR here: https://github.com/Eriner/zim/pull/104. Now all that is left is to integrate this functionality into the other prompts where applicable.

**Comment by stefanosc** [comment]
I followed the conversation, thank you both!

**Comment by ericbn** [comment]
In the path of getting to "unify all of the prompts to use a single set of universal functions" (https://github.com/Eriner/zim/issues/82#issuecomment-250028706) I'm proposing a migration of the eriner theme at #142. There are still others to go...

**Comment by ericbn** [comment]
Proposing a migration of the minimal theme at https://github.com/Eriner/zim/pull/152. Just steeef left to go.

**Comment by ericbn** [comment]
All themes are migrated to git-info now. 🍾 
I think this can be closed.
