### ISSUE TITLE
Binding to empty key sequences when starting zim using Termite and Urxvt

### ISSUE THREAD

**Issue by Tmplt** [Eriner/zim#83]
- Zim commit ref: 071ddaf0acd38e3d9b453717bfa52a344e6d15d4
- gist of .zimrc: https://ptpb.pw/FTD0
- Zsh version: zsh 5.2 (x86_64-unknown-linux-gnu)
- gist of .zshrc: https://github.com/Tmplt/dotfiles/blob/desktop/zsh/.zshrc
- `$(uname -mosr)`: Linux 4.7.4-1-zen x86_64 GNU/Linux

Description
-----------
Some keybindings for `modules/{input,history-substring-search}` do not work in [Termite](https://github.com/thestinger/termite). 

Granted, this means that some features do not work in Termite, however, using `tmux` fixes it.

Steps to reproduce
------------------
Open `termite` which uses zim; the following will be printed:

```
/home/tmplt/.zim/modules/input/init.zsh:bindkey:91: cannot bind to an empty key sequence
/home/tmplt/.zim/modules/input/init.zsh:bindkey:92: cannot bind to an empty key sequence
/home/tmplt/.zim/modules/history-substring-search/init.zsh:bindkey:14: cannot bind to an empty key sequence
/home/tmplt/.zim/modules/history-substring-search/init.zsh:bindkey:15: cannot bind to an empty key sequence
```

**Comment by Eriner** [comment]
I don't use this emulator and I'm not really one for debugging these (implementation specific) issues. If you can find a solution, please submit a PR and I'll gladly merge it, provided it doesn't break other terminals.

**Comment by Tmplt** [comment]
It's worth noting that while the error messages aren't printed in it, the keybinds do not work (`Left` skips over whole words, and `Up` doesn't use substring history) in `urxvt` for me. They do work in `st` and `xterm`, though.

Is anyone able to replicate this?

**Comment by Eriner** [comment]
`(u)rxvt` is seemingly the devil of compatibility, so I'm not surprised that it also has issues. Please let me know if you do find a fix for these terminals (probably different bind chars?) and I'll merge it as soon as possible.

**Comment by Tmplt** [comment]
Playing around with `echoti` within `.zim/modules/input/init.zsh` it appears that these keybinds are not possible in both `termite` and `urxvt`:
- `key_info[Up]`,
- `key_info[Down]`,
- `key_info[Left]` and
- `key_info[Right]`.

E.g., running `echoti kccu1` somewhere in `input/init.zsh` prints nothing. However, running it after `zim` has started up prints expected results.

The results are the same if I'd move `input` to the tail-end of `zmodules` in `~/.zimrc`, in case module load order mattered, but that's not the case.

I'll dabble with this more tomorrow unless it's been solved by then.

**Comment by Tmplt** [comment]
This might be an issue with my system. Termite works as expected on my laptop (however, configs are practically the same), urxvt does not, though.

Could someone install `termite`, load `input` and check whether the `{Up,Down,Left,Right}` keybinds works?

**Comment by Eriner** [comment]
@Tmplt I cannot reproduce this issue with termite on my system (no changes to dotfiles). It also functions as expected with the default configuration (from `templates` folder). I have not tested rxvt.

**Comment by Tmplt** [comment]
I had `aur/termite-ranger-fix-terminfo-git` installed, which I hadn't updated in a while. Updating it (`pacaur -S termite-ranger-fix-terminfo-git`) fixed the issue.

This is still an issue for `urxvt`, though. I'll open a new issue for that.
