### ISSUE TITLE
Investigate usage of zrecompile for zlogin

### ISSUE THREAD

**Issue by Eriner** [Eriner/zim#86]
See documentation here: http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Recompiling-Functions

Currently, `.zlogin` checks specific functions that are "heavy" and could actually benefit from `zcompile`. I have also implemented an "if source newer than compiled" function to check if zcompile is required. Seemingly, this functionality is already provided by zsh and need only be autoloaded. My current implementation can be seen below:

```
  # Function to determine the need of a zcompile. If the .zwc file
  # does not exist, or the base file is newer, we need to compile.
  # These jobs are asynchronous, and will not impact the interactive shell
  zcompare() {
    if [[ -s ${1} && ( ! -s ${1}.zwc || ${1} -nt ${1}.zwc) ]]; then
      zcompile ${1}
    fi
  }
```

Replacing `zcompare` with `zrecompile` (or a loose wrapper) may or may not be useful. This is something to be investigated.

**Comment by dezza** [comment]
In my experience avoiding zrecompile was much faster and noticeable for me.

**Comment by Eriner** [comment]
That may be less of an issue with `zrecompile` itself an more of an issue with how zsh operates.

> If you frequently edit your zsh functions, or periodically update your zsh installation to track the latest developments, you may find that function digests compiled with the zcompile builtin are frequently out of date with respect to the function source files. This is not usually a problem, because **zsh always looks for the newest file when loading a function, but it may cause slower shell startup and function loading.**

Emphasis mine. I still believe that using `zrecompile` and digesting entire modules into a single zwc (as opposed to only the "heavy" functions) is the way to go, but to confirm my suspicion, I'd need to do practical testing.

**Comment by ericbn** [comment]
Just did a comparison of `zcompare` vs. `zrecompile -pq`:

| | zcompare | zrecompile |
|---|---|---|
| none compiled (will compile all) | 0.020s | 0.022s |
| all compiled (will compile none) | 0.007s | 0.045s |

using

```
Zim commit ref:   a4f6b75
Zsh version:      zsh 5.4.2 (x86_64-apple-darwin15.6.0)
System info:      Darwin ericsmacbookpro.local 15.6.0 Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64 x86_64
```

**Comment by Eriner** [comment]
Yes, `zrecompile` will take more time, especially if we're using it to compile _all_ files in a folder into a single digest. However, this isn't an issue at login (at least, we're talking <1s time) as `.zlogin` should only really be read once per boot (at TTY login), so this isn't a huge deal. However, seeing as we have many files per module, compiling them into a single file, while an upfront investment, should reduce the amount of files the shell has to Open() and Read() during each shell creation, which especially in cases of under-performant disks, could shave off a significant percentage of initialization time for each shell.

**Comment by NightMachinary** [comment]
I have a lot of zsh files full of functions (so there are multiple functions in a single file). Is it possible to automatically compile these files? Looking at `zcompile`'s docs, it seems it only works with "autoloadable" function files? Perhaps something that creates a compiled file of everything in `$functions` is possible?
