### ISSUE TITLE
How to remove Machine name from prompt?

### ISSUE THREAD

**Issue by jitendravyas** [Eriner/zim#97]
zsh 5.2 (x86_64-apple-darwin14.5.0)
macOS sierra

I found this http://stackoverflow.com/questions/31848957/zsh-hide-computer-name-in-the-terminal but I don't have these entries in my .zshrc

![image](https://cloud.githubusercontent.com/assets/77309/19619648/197e9ba8-988a-11e6-9c65-52ae8a77443c.png)

**Comment by Tmplt** [comment]
You're using the `steeef` theme, which prints `hostname` in the prompt. Not all prompts in `zim` does this, though.

You can find all available prompts (and preview them) with `prompt -p`, which you can then set with `zprompt_theme` in `~/.zimrc`.

**Comment by jitendravyas** [comment]
Thanks for reply. Is there an easy way to hide machine from any theme I like but has machine name?

**Comment by Tmplt** [comment]
At present, themes do not support options; perhaps that should be a thing (pinging @Eriner)?

If you want to use a theme and strip out the hostname, you'll have to change the respective theme file in `modules/prompt/{external-,}themes`. For example: in `steeef`, you'll have to remove `at %{$orange%}%m${${reset_color}%}` in `PROMPT` on [line 44](https://github.com/Eriner/zim/blob/master/modules/prompt/themes/steeef.zsh-theme#L44).

**Comment by Eriner** [comment]
> At present, themes do not support options; perhaps that should be a thing (pinging @Eriner)?

If the theme you're using supports options, cool. The current theme's don't, and unless someone wants to do the work to make that happen, just fork or find a different theme.
