### ISSUE TITLE
Couldn't read file /Users/jitendravyas/.zim/modules/prompt/functions/prompt_lean_setup containing theme lean.

### ISSUE THREAD

**Issue by jitendravyas** [Eriner/zim#98]
I have recently updated my Zim and added almost all modules. I'm getting this error in terminal

`Couldn't read file /Users/jitendravyas/.zim/modules/prompt/functions/prompt_lean_setup containing theme lean.
`

```
zmodules=(directory environment git history input utility custom \
          syntax-highlighting history-substring-search prompt completion spectrum archive ssh)
```

I had used `prompt minimal -s` too

![image](https://cloud.githubusercontent.com/assets/77309/19620384/f7082e44-9899-11e6-8676-63fa34920f10.png)

**Comment by Tmplt** [comment]
Probably the same issue as #73; try updating the submodules: `$ zmanage update`.

If you're using an outdated version of `zim`: `$ cd ~/.zim && git submodule update --init --recursive`.

**Comment by jitendravyas** [comment]
I'm using latest Zim but I tried both command you suggested. it seems that error has gone but I still get this. It looks like themes are not applying. I have ran this many times `prompt minimal -s`

![image](https://cloud.githubusercontent.com/assets/77309/19621993/9b5f9b72-98bc-11e6-9c83-50ffa00241ab.png)

**Comment by Tmplt** [comment]
You must set `zprompt_theme='minimal'` in `~/.zimrc`; `prompt -s` is not implemented yet.

**Comment by jitendravyas** [comment]
Theme name was already set in `.zimrc` but I found that theme name is case sensitive that's why it was not working. 

I was using `zprompt_theme='Minimal'` instead `zprompt_theme='minimal'`
It's fine now. Thanks.
